
 //Generated By XCodeFactory
package org.guihuotv.search.web.pojo;

import uw.dm.util.*;
import java.util.*;
import java.io.Serializable;

/**
 * Title: Base table MscUser的pojo类
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为ValueObject类，通过数据库表映像。
 */
public class MscUser implements Serializable,Cloneable {

	private static final long serialVersionUID = 1L;
	
	/*
	 * 字段，类型map表
	 */
	public static final HashMap<String, Integer> MAP_COL_TYPE = new HashMap<String, Integer>();
	
	/*
	 * 原始名称，属性名称map表
	 */
	public static final HashMap<String, String> MAP_COL_NAME = new HashMap<String, String>();
	
	 
	static{
		
		MAP_COL_TYPE.put("id",DmObjectType.LONG);
		MAP_COL_NAME.put("id","id");
		
		MAP_COL_TYPE.put("username",DmObjectType.STRING);
		MAP_COL_NAME.put("username","username");
		
		MAP_COL_TYPE.put("passwd",DmObjectType.STRING);
		MAP_COL_NAME.put("passwd","passwd");
		
		MAP_COL_TYPE.put("msc_perm",DmObjectType.STRING);
		MAP_COL_NAME.put("msc_perm","mscPerm");
		
		MAP_COL_TYPE.put("org_perm",DmObjectType.STRING);
		MAP_COL_NAME.put("org_perm","orgPerm");
		
		MAP_COL_TYPE.put("org_name",DmObjectType.STRING);
		MAP_COL_NAME.put("org_name","orgName");
		
		MAP_COL_TYPE.put("alias_name",DmObjectType.STRING);
		MAP_COL_NAME.put("alias_name","aliasName");
		
		MAP_COL_TYPE.put("telephone",DmObjectType.STRING);
		MAP_COL_NAME.put("telephone","telephone");
		
		MAP_COL_TYPE.put("mobile",DmObjectType.STRING);
		MAP_COL_NAME.put("mobile","mobile");
		
		MAP_COL_TYPE.put("email",DmObjectType.STRING);
		MAP_COL_NAME.put("email","email");
		
		MAP_COL_TYPE.put("last_logon_date",DmObjectType.DATE);
		MAP_COL_NAME.put("last_logon_date","lastLogonDate");
		
		MAP_COL_TYPE.put("last_logon_ip",DmObjectType.STRING);
		MAP_COL_NAME.put("last_logon_ip","lastLogonIp");
		
		MAP_COL_TYPE.put("create_date",DmObjectType.DATE);
		MAP_COL_NAME.put("create_date","createDate");
		
		MAP_COL_TYPE.put("modify_date",DmObjectType.DATE);
		MAP_COL_NAME.put("modify_date","modifyDate");
		
		MAP_COL_TYPE.put("status",DmObjectType.INT);
		MAP_COL_NAME.put("status","status");
		
	}

	public static final String TABLE_NAME = "msc_user";
	
	
	public static final String COL_ID = "id";
	
	public static final String COL_USERNAME = "username";
	
	public static final String COL_PASSWD = "passwd";
	
	public static final String COL_MSC_PERM = "msc_perm";
	
	public static final String COL_ORG_PERM = "org_perm";
	
	public static final String COL_ORG_NAME = "org_name";
	
	public static final String COL_ALIAS_NAME = "alias_name";
	
	public static final String COL_TELEPHONE = "telephone";
	
	public static final String COL_MOBILE = "mobile";
	
	public static final String COL_EMAIL = "email";
	
	public static final String COL_LAST_LOGON_DATE = "last_logon_date";
	
	public static final String COL_LAST_LOGON_IP = "last_logon_ip";
	
	public static final String COL_CREATE_DATE = "create_date";
	
	public static final String COL_MODIFY_DATE = "modify_date";
	
	public static final String COL_STATUS = "status";
	

	/*
	 * 轻量级状态下更新列表list
	 */
	public List<String> LIST_COL_UPDATED = null;
	
	/*
	 * 自定义的附属信息
	 */
	public Map<Object,Object> MAP_EXT_PROPERTY = null;
	
	/*
	 * 变更信息
	 */
	private StringBuilder _CHANGED_INFO = null;
	
	/*
	 * 分割行
	 */
	private static final String _SEPARATE_LINE = "************************************\r\n";
	

	/*
	 * 实际的表名
	 */
	public String CURRENT_TABLE_NAME = null;
	
	
	//属性定义区域
	
	
	/**
	 * ID
	 */
	private long id = 0l;
	
	
	/**
	 * 登录的用户名
	 */
	private String username = "";
	
	
	/**
	 * 登录的密码
	 */
	private String passwd = "";
	
	
	/**
	 * 对应菜单权限
	 */
	private String mscPerm = "";
	
	
	/**
	 * 可管理单位的权限
	 */
	private String orgPerm = "";
	
	
	/**
	 * 单位名称
	 */
	private String orgName = "";
	
	
	/**
	 * 联系人
	 */
	private String aliasName = "";
	
	
	/**
	 * 电话
	 */
	private String telephone = "";
	
	
	/**
	 * 手机
	 */
	private String mobile = "";
	
	
	/**
	 * Email
	 */
	private String email = "";
	
	
	/**
	 * 最后登录时间
	 */
	private java.util.Date lastLogonDate = null;
	
	
	/**
	 * 最后登录IP
	 */
	private String lastLogonIp = "";
	
	
	/**
	 * 建立时间
	 */
	private java.util.Date createDate = null;
	
	
	/**
	 * 最后修改时间
	 */
	private java.util.Date modifyDate = null;
	
	
	/**
	 * 状态
	 */
	private int status = 0;
	
	
	/**
	 * 设置附加属性
	 */
	public void SET_EXT_PROPERTY(Object key,Object value){
		if (MAP_EXT_PROPERTY==null)
			MAP_EXT_PROPERTY = new LinkedHashMap<Object,Object>();
		MAP_EXT_PROPERTY.put(key,value);
	}
	
	/**
	 * 获得附加属性
	 */
	public Object GET_EXT_PROPERTY(Object key){
		if (MAP_EXT_PROPERTY!=null)
			return MAP_EXT_PROPERTY.get(key);
		else
			return null;
	}
	
	/**
	 * 获得附加属性MAP
	 */
	public Map<Object,Object> GET_EXT_PROPERTY_MAP(){
		return MAP_EXT_PROPERTY;
	}
	
	/**
	 * 获得更改的字段列表.
	 */
	public List<String> GET_UPDATED_COL_LIST(){
		return LIST_COL_UPDATED;
	}
	
	/**
	 * 得到_CHANGED_INFO
	 */
	public String GET_CHANGED_INFO(){
		if (this._CHANGED_INFO==null){
			return null;
		}else{
			this._CHANGED_INFO.append(_SEPARATE_LINE);
			return this._CHANGED_INFO.toString(); 
		}
	}
	
	
	/**
	 * 获取ID数值
	 */
	public long getId()
	{
		return this.id;
	}
	
	/**
	 * 获取登录的用户名数值
	 */
	public String getUsername()
	{
		return this.username;
	}
	
	/**
	 * 获取登录的密码数值
	 */
	public String getPasswd()
	{
		return this.passwd;
	}
	
	/**
	 * 获取对应菜单权限数值
	 */
	public String getMscPerm()
	{
		return this.mscPerm;
	}
	
	/**
	 * 获取可管理单位的权限数值
	 */
	public String getOrgPerm()
	{
		return this.orgPerm;
	}
	
	/**
	 * 获取单位名称数值
	 */
	public String getOrgName()
	{
		return this.orgName;
	}
	
	/**
	 * 获取联系人数值
	 */
	public String getAliasName()
	{
		return this.aliasName;
	}
	
	/**
	 * 获取电话数值
	 */
	public String getTelephone()
	{
		return this.telephone;
	}
	
	/**
	 * 获取手机数值
	 */
	public String getMobile()
	{
		return this.mobile;
	}
	
	/**
	 * 获取Email数值
	 */
	public String getEmail()
	{
		return this.email;
	}
	
	/**
	 * 获取最后登录时间数值
	 */
	public java.util.Date getLastLogonDate()
	{
		return this.lastLogonDate;
	}
	
	/**
	 * 获取最后登录IP数值
	 */
	public String getLastLogonIp()
	{
		return this.lastLogonIp;
	}
	
	/**
	 * 获取建立时间数值
	 */
	public java.util.Date getCreateDate()
	{
		return this.createDate;
	}
	
	/**
	 * 获取最后修改时间数值
	 */
	public java.util.Date getModifyDate()
	{
		return this.modifyDate;
	}
	
	/**
	 * 获取状态数值
	 */
	public int getStatus()
	{
		return this.status;
	}
	

	
	/**
	 * 初始化set相关的信息
	 */
	private void initSetInfo(){
			this.LIST_COL_UPDATED = new ArrayList<String>();
			this._CHANGED_INFO = new StringBuilder(_SEPARATE_LINE+"表MscUser，主键\""+this.id+"\"变更信息为:\r\n");
	}

	
	/**
	 * 设置ID数值
	 */
	public void setId(long id)
	{
		if (this.id!=id){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("id")){ 
				this.LIST_COL_UPDATED.add("id");
			}
			this._CHANGED_INFO.append("字段id由\""+this.id+"\"修改为\""+id+"\"\r\n");
			this.id = id;
		}
	}
	
	/**
	 * 设置登录的用户名数值
	 */
	public void setUsername(String username)
	{
		if ((!String.valueOf(this.username).equals(String.valueOf(username)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("username")){ 
				this.LIST_COL_UPDATED.add("username");
			}
			this._CHANGED_INFO.append("字段username由\""+this.username+"\"修改为\""+username+"\"\r\n");
			this.username = username;
		}
	}
	
	/**
	 * 设置登录的密码数值
	 */
	public void setPasswd(String passwd)
	{
		if ((!String.valueOf(this.passwd).equals(String.valueOf(passwd)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("passwd")){ 
				this.LIST_COL_UPDATED.add("passwd");
			}
			this._CHANGED_INFO.append("字段passwd由\""+this.passwd+"\"修改为\""+passwd+"\"\r\n");
			this.passwd = passwd;
		}
	}
	
	/**
	 * 设置对应菜单权限数值
	 */
	public void setMscPerm(String mscPerm)
	{
		if ((!String.valueOf(this.mscPerm).equals(String.valueOf(mscPerm)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("msc_perm")){ 
				this.LIST_COL_UPDATED.add("msc_perm");
			}
			this._CHANGED_INFO.append("字段msc_perm由\""+this.mscPerm+"\"修改为\""+mscPerm+"\"\r\n");
			this.mscPerm = mscPerm;
		}
	}
	
	/**
	 * 设置可管理单位的权限数值
	 */
	public void setOrgPerm(String orgPerm)
	{
		if ((!String.valueOf(this.orgPerm).equals(String.valueOf(orgPerm)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("org_perm")){ 
				this.LIST_COL_UPDATED.add("org_perm");
			}
			this._CHANGED_INFO.append("字段org_perm由\""+this.orgPerm+"\"修改为\""+orgPerm+"\"\r\n");
			this.orgPerm = orgPerm;
		}
	}
	
	/**
	 * 设置单位名称数值
	 */
	public void setOrgName(String orgName)
	{
		if ((!String.valueOf(this.orgName).equals(String.valueOf(orgName)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("org_name")){ 
				this.LIST_COL_UPDATED.add("org_name");
			}
			this._CHANGED_INFO.append("字段org_name由\""+this.orgName+"\"修改为\""+orgName+"\"\r\n");
			this.orgName = orgName;
		}
	}
	
	/**
	 * 设置联系人数值
	 */
	public void setAliasName(String aliasName)
	{
		if ((!String.valueOf(this.aliasName).equals(String.valueOf(aliasName)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("alias_name")){ 
				this.LIST_COL_UPDATED.add("alias_name");
			}
			this._CHANGED_INFO.append("字段alias_name由\""+this.aliasName+"\"修改为\""+aliasName+"\"\r\n");
			this.aliasName = aliasName;
		}
	}
	
	/**
	 * 设置电话数值
	 */
	public void setTelephone(String telephone)
	{
		if ((!String.valueOf(this.telephone).equals(String.valueOf(telephone)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("telephone")){ 
				this.LIST_COL_UPDATED.add("telephone");
			}
			this._CHANGED_INFO.append("字段telephone由\""+this.telephone+"\"修改为\""+telephone+"\"\r\n");
			this.telephone = telephone;
		}
	}
	
	/**
	 * 设置手机数值
	 */
	public void setMobile(String mobile)
	{
		if ((!String.valueOf(this.mobile).equals(String.valueOf(mobile)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("mobile")){ 
				this.LIST_COL_UPDATED.add("mobile");
			}
			this._CHANGED_INFO.append("字段mobile由\""+this.mobile+"\"修改为\""+mobile+"\"\r\n");
			this.mobile = mobile;
		}
	}
	
	/**
	 * 设置Email数值
	 */
	public void setEmail(String email)
	{
		if ((!String.valueOf(this.email).equals(String.valueOf(email)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("email")){ 
				this.LIST_COL_UPDATED.add("email");
			}
			this._CHANGED_INFO.append("字段email由\""+this.email+"\"修改为\""+email+"\"\r\n");
			this.email = email;
		}
	}
	
	/**
	 * 设置最后登录时间数值
	 */
	public void setLastLogonDate(java.util.Date lastLogonDate)
	{
		if ((this.lastLogonDate!=null&&lastLogonDate!=null&&!this.lastLogonDate.equals(lastLogonDate))||(this.lastLogonDate!=lastLogonDate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("last_logon_date")){ 
				this.LIST_COL_UPDATED.add("last_logon_date");
			}
			this._CHANGED_INFO.append("字段last_logon_date由\""+this.lastLogonDate+"\"修改为\""+lastLogonDate+"\"\r\n");
			this.lastLogonDate = lastLogonDate;
		}
	}
	
	/**
	 * 设置最后登录IP数值
	 */
	public void setLastLogonIp(String lastLogonIp)
	{
		if ((!String.valueOf(this.lastLogonIp).equals(String.valueOf(lastLogonIp)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("last_logon_ip")){ 
				this.LIST_COL_UPDATED.add("last_logon_ip");
			}
			this._CHANGED_INFO.append("字段last_logon_ip由\""+this.lastLogonIp+"\"修改为\""+lastLogonIp+"\"\r\n");
			this.lastLogonIp = lastLogonIp;
		}
	}
	
	/**
	 * 设置建立时间数值
	 */
	public void setCreateDate(java.util.Date createDate)
	{
		if ((this.createDate!=null&&createDate!=null&&!this.createDate.equals(createDate))||(this.createDate!=createDate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("create_date")){ 
				this.LIST_COL_UPDATED.add("create_date");
			}
			this._CHANGED_INFO.append("字段create_date由\""+this.createDate+"\"修改为\""+createDate+"\"\r\n");
			this.createDate = createDate;
		}
	}
	
	/**
	 * 设置最后修改时间数值
	 */
	public void setModifyDate(java.util.Date modifyDate)
	{
		if ((this.modifyDate!=null&&modifyDate!=null&&!this.modifyDate.equals(modifyDate))||(this.modifyDate!=modifyDate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("modify_date")){ 
				this.LIST_COL_UPDATED.add("modify_date");
			}
			this._CHANGED_INFO.append("字段modify_date由\""+this.modifyDate+"\"修改为\""+modifyDate+"\"\r\n");
			this.modifyDate = modifyDate;
		}
	}
	
	/**
	 * 设置状态数值
	 */
	public void setStatus(int status)
	{
		if (this.status!=status){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("status")){ 
				this.LIST_COL_UPDATED.add("status");
			}
			this._CHANGED_INFO.append("字段status由\""+this.status+"\"修改为\""+status+"\"\r\n");
			this.status = status;
		}
	}
	
	

	/**
	 * 构造器
	 */
	public MscUser(long id,String username,String passwd,String mscPerm,String orgPerm,String orgName,String aliasName,String telephone,String mobile,String email,java.util.Date lastLogonDate,String lastLogonIp,java.util.Date createDate,java.util.Date modifyDate,int status){
	
		this.id = id;
		this.username = username;
		this.passwd = passwd;
		this.mscPerm = mscPerm;
		this.orgPerm = orgPerm;
		this.orgName = orgName;
		this.aliasName = aliasName;
		this.telephone = telephone;
		this.mobile = mobile;
		this.email = email;
		this.lastLogonDate = lastLogonDate;
		this.lastLogonIp = lastLogonIp;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.status = status;
		
	}
	
	/**
	 * 构造器
	 */
	public MscUser(){
	}
	

	
	/**
	 * 重载toString方法
	 */
	public String toString(){
		StringBuilder sb = new StringBuilder(_SEPARATE_LINE+"表MscUser，主键\""+this.id+"\"的全部信息为:\r\n");
		sb.append("字段id数值为:"+id+"\r\n");
		sb.append("字段username数值为:"+username+"\r\n");
		sb.append("字段passwd数值为:"+passwd+"\r\n");
		sb.append("字段msc_perm数值为:"+mscPerm+"\r\n");
		sb.append("字段org_perm数值为:"+orgPerm+"\r\n");
		sb.append("字段org_name数值为:"+orgName+"\r\n");
		sb.append("字段alias_name数值为:"+aliasName+"\r\n");
		sb.append("字段telephone数值为:"+telephone+"\r\n");
		sb.append("字段mobile数值为:"+mobile+"\r\n");
		sb.append("字段email数值为:"+email+"\r\n");
		sb.append("字段last_logon_date数值为:"+lastLogonDate+"\r\n");
		sb.append("字段last_logon_ip数值为:"+lastLogonIp+"\r\n");
		sb.append("字段create_date数值为:"+createDate+"\r\n");
		sb.append("字段modify_date数值为:"+modifyDate+"\r\n");
		sb.append("字段status数值为:"+status+"\r\n");
		
		sb.append(_SEPARATE_LINE);
		return sb.toString();
	}

	/**
	* 克隆自身
	* @return<a name=""></a>
	*/
	public Object clone(){
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {}
		return o;
	}

	
}