
 //Generated By XCodeFactory
package org.guihuotv.search.web.pojo;

import uw.dm.util.*;
import java.util.*;
import java.io.Serializable;

/**
 * Title: Base table NgnMsg的pojo类
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为ValueObject类，通过数据库表映像。
 */
public class NgnMsg implements Serializable,Cloneable {

	private static final long serialVersionUID = 1L;
	
	/*
	 * 字段，类型map表
	 */
	public static final HashMap<String, Integer> MAP_COL_TYPE = new HashMap<String, Integer>();
	
	/*
	 * 原始名称，属性名称map表
	 */
	public static final HashMap<String, String> MAP_COL_NAME = new HashMap<String, String>();
	
	 
	static{
		
		MAP_COL_TYPE.put("id",DmObjectType.LONG);
		MAP_COL_NAME.put("id","id");
		
		MAP_COL_TYPE.put("userid",DmObjectType.LONG);
		MAP_COL_NAME.put("userid","userid");
		
		MAP_COL_TYPE.put("touserid",DmObjectType.LONG);
		MAP_COL_NAME.put("touserid","touserid");
		
		MAP_COL_TYPE.put("msg",DmObjectType.STRING);
		MAP_COL_NAME.put("msg","msg");
		
		MAP_COL_TYPE.put("senddate",DmObjectType.DATE);
		MAP_COL_NAME.put("senddate","senddate");
		
		MAP_COL_TYPE.put("status",DmObjectType.INT);
		MAP_COL_NAME.put("status","status");
		
	}

	public static final String TABLE_NAME = "ngn_msg";
	
	
	public static final String COL_ID = "id";
	
	public static final String COL_USERID = "userid";
	
	public static final String COL_TOUSERID = "touserid";
	
	public static final String COL_MSG = "msg";
	
	public static final String COL_SENDDATE = "senddate";
	
	public static final String COL_STATUS = "status";
	

	/*
	 * 轻量级状态下更新列表list
	 */
	public List<String> LIST_COL_UPDATED = null;
	
	/*
	 * 自定义的附属信息
	 */
	public Map<Object,Object> MAP_EXT_PROPERTY = null;
	
	/*
	 * 变更信息
	 */
	private StringBuilder _CHANGED_INFO = null;
	
	/*
	 * 分割行
	 */
	private static final String _SEPARATE_LINE = "************************************\r\n";
	

	/*
	 * 实际的表名
	 */
	public String CURRENT_TABLE_NAME = null;
	
	
	//属性定义区域
	
	
	/**
	 * ID
	 */
	private long id = 0l;
	
	
	/**
	 * 发送者ID
	 */
	private long userid = 0l;
	
	
	/**
	 * 接收者ID
	 */
	private long touserid = 0l;
	
	
	/**
	 * 消息内容
	 */
	private String msg = "";
	
	
	/**
	 * 发送日期
	 */
	private java.util.Date senddate = null;
	
	
	/**
	 * 状态
	 */
	private int status = 0;
	
	
	/**
	 * 设置附加属性
	 */
	public void SET_EXT_PROPERTY(Object key,Object value){
		if (MAP_EXT_PROPERTY==null)
			MAP_EXT_PROPERTY = new LinkedHashMap<Object,Object>();
		MAP_EXT_PROPERTY.put(key,value);
	}
	
	/**
	 * 获得附加属性
	 */
	public Object GET_EXT_PROPERTY(Object key){
		if (MAP_EXT_PROPERTY!=null)
			return MAP_EXT_PROPERTY.get(key);
		else
			return null;
	}
	
	/**
	 * 获得附加属性MAP
	 */
	public Map<Object,Object> GET_EXT_PROPERTY_MAP(){
		return MAP_EXT_PROPERTY;
	}
	
	/**
	 * 获得更改的字段列表.
	 */
	public List<String> GET_UPDATED_COL_LIST(){
		return LIST_COL_UPDATED;
	}
	
	/**
	 * 得到_CHANGED_INFO
	 */
	public String GET_CHANGED_INFO(){
		if (this._CHANGED_INFO==null){
			return null;
		}else{
			this._CHANGED_INFO.append(_SEPARATE_LINE);
			return this._CHANGED_INFO.toString(); 
		}
	}
	
	
	/**
	 * 获取ID数值
	 */
	public long getId()
	{
		return this.id;
	}
	
	/**
	 * 获取发送者ID数值
	 */
	public long getUserid()
	{
		return this.userid;
	}
	
	/**
	 * 获取接收者ID数值
	 */
	public long getTouserid()
	{
		return this.touserid;
	}
	
	/**
	 * 获取消息内容数值
	 */
	public String getMsg()
	{
		return this.msg;
	}
	
	/**
	 * 获取发送日期数值
	 */
	public java.util.Date getSenddate()
	{
		return this.senddate;
	}
	
	/**
	 * 获取状态数值
	 */
	public int getStatus()
	{
		return this.status;
	}
	

	
	/**
	 * 初始化set相关的信息
	 */
	private void initSetInfo(){
			this.LIST_COL_UPDATED = new ArrayList<String>();
			this._CHANGED_INFO = new StringBuilder(_SEPARATE_LINE+"表NgnMsg，主键\""+this.id+"\"变更信息为:\r\n");
	}

	
	/**
	 * 设置ID数值
	 */
	public void setId(long id)
	{
		if (this.id!=id){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("id")){ 
				this.LIST_COL_UPDATED.add("id");
			}
			this._CHANGED_INFO.append("字段id由\""+this.id+"\"修改为\""+id+"\"\r\n");
			this.id = id;
		}
	}
	
	/**
	 * 设置发送者ID数值
	 */
	public void setUserid(long userid)
	{
		if (this.userid!=userid){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("userid")){ 
				this.LIST_COL_UPDATED.add("userid");
			}
			this._CHANGED_INFO.append("字段userid由\""+this.userid+"\"修改为\""+userid+"\"\r\n");
			this.userid = userid;
		}
	}
	
	/**
	 * 设置接收者ID数值
	 */
	public void setTouserid(long touserid)
	{
		if (this.touserid!=touserid){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("touserid")){ 
				this.LIST_COL_UPDATED.add("touserid");
			}
			this._CHANGED_INFO.append("字段touserid由\""+this.touserid+"\"修改为\""+touserid+"\"\r\n");
			this.touserid = touserid;
		}
	}
	
	/**
	 * 设置消息内容数值
	 */
	public void setMsg(String msg)
	{
		if ((!String.valueOf(this.msg).equals(String.valueOf(msg)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("msg")){ 
				this.LIST_COL_UPDATED.add("msg");
			}
			this._CHANGED_INFO.append("字段msg由\""+this.msg+"\"修改为\""+msg+"\"\r\n");
			this.msg = msg;
		}
	}
	
	/**
	 * 设置发送日期数值
	 */
	public void setSenddate(java.util.Date senddate)
	{
		if ((this.senddate!=null&&senddate!=null&&!this.senddate.equals(senddate))||(this.senddate!=senddate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("senddate")){ 
				this.LIST_COL_UPDATED.add("senddate");
			}
			this._CHANGED_INFO.append("字段senddate由\""+this.senddate+"\"修改为\""+senddate+"\"\r\n");
			this.senddate = senddate;
		}
	}
	
	/**
	 * 设置状态数值
	 */
	public void setStatus(int status)
	{
		if (this.status!=status){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("status")){ 
				this.LIST_COL_UPDATED.add("status");
			}
			this._CHANGED_INFO.append("字段status由\""+this.status+"\"修改为\""+status+"\"\r\n");
			this.status = status;
		}
	}
	
	

	/**
	 * 构造器
	 */
	public NgnMsg(long id,long userid,long touserid,String msg,java.util.Date senddate,int status){
	
		this.id = id;
		this.userid = userid;
		this.touserid = touserid;
		this.msg = msg;
		this.senddate = senddate;
		this.status = status;
		
	}
	
	/**
	 * 构造器
	 */
	public NgnMsg(){
	}
	

	
	/**
	 * 重载toString方法
	 */
	public String toString(){
		StringBuilder sb = new StringBuilder(_SEPARATE_LINE+"表NgnMsg，主键\""+this.id+"\"的全部信息为:\r\n");
		sb.append("字段id数值为:"+id+"\r\n");
		sb.append("字段userid数值为:"+userid+"\r\n");
		sb.append("字段touserid数值为:"+touserid+"\r\n");
		sb.append("字段msg数值为:"+msg+"\r\n");
		sb.append("字段senddate数值为:"+senddate+"\r\n");
		sb.append("字段status数值为:"+status+"\r\n");
		
		sb.append(_SEPARATE_LINE);
		return sb.toString();
	}

	/**
	* 克隆自身
	* @return<a name=""></a>
	*/
	public Object clone(){
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {}
		return o;
	}

	
}