
 //Generated By XCodeFactory
package org.guihuotv.search.web.pojo;

import uw.dm.util.*;
import java.util.*;
import java.io.Serializable;

/**
 * Title: Base table NgnSay的pojo类
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为ValueObject类，通过数据库表映像。
 */
public class NgnSay implements Serializable,Cloneable {

	private static final long serialVersionUID = 1L;
	
	/*
	 * 字段，类型map表
	 */
	public static final HashMap<String, Integer> MAP_COL_TYPE = new HashMap<String, Integer>();
	
	/*
	 * 原始名称，属性名称map表
	 */
	public static final HashMap<String, String> MAP_COL_NAME = new HashMap<String, String>();
	
	 
	static{
		
		MAP_COL_TYPE.put("id",DmObjectType.LONG);
		MAP_COL_NAME.put("id","id");
		
		MAP_COL_TYPE.put("usersay",DmObjectType.STRING);
		MAP_COL_NAME.put("usersay","usersay");
		
		MAP_COL_TYPE.put("syscmd",DmObjectType.STRING);
		MAP_COL_NAME.put("syscmd","syscmd");
		
		MAP_COL_TYPE.put("cmdcontent",DmObjectType.STRING);
		MAP_COL_NAME.put("cmdcontent","cmdcontent");
		
		MAP_COL_TYPE.put("cmdp1",DmObjectType.STRING);
		MAP_COL_NAME.put("cmdp1","cmdp1");
		
		MAP_COL_TYPE.put("cmdp2",DmObjectType.STRING);
		MAP_COL_NAME.put("cmdp2","cmdp2");
		
		MAP_COL_TYPE.put("cmdp3",DmObjectType.STRING);
		MAP_COL_NAME.put("cmdp3","cmdp3");
		
		MAP_COL_TYPE.put("cmdp4",DmObjectType.STRING);
		MAP_COL_NAME.put("cmdp4","cmdp4");
		
		MAP_COL_TYPE.put("cmdp5",DmObjectType.STRING);
		MAP_COL_NAME.put("cmdp5","cmdp5");
		
		MAP_COL_TYPE.put("createtime",DmObjectType.DATE);
		MAP_COL_NAME.put("createtime","createtime");
		
		MAP_COL_TYPE.put("status",DmObjectType.INT);
		MAP_COL_NAME.put("status","status");
		
	}

	public static final String TABLE_NAME = "ngn_say";
	
	
	public static final String COL_ID = "id";
	
	public static final String COL_USERSAY = "usersay";
	
	public static final String COL_SYSCMD = "syscmd";
	
	public static final String COL_CMDCONTENT = "cmdcontent";
	
	public static final String COL_CMDP1 = "cmdp1";
	
	public static final String COL_CMDP2 = "cmdp2";
	
	public static final String COL_CMDP3 = "cmdp3";
	
	public static final String COL_CMDP4 = "cmdp4";
	
	public static final String COL_CMDP5 = "cmdp5";
	
	public static final String COL_CREATETIME = "createtime";
	
	public static final String COL_STATUS = "status";
	

	/*
	 * 轻量级状态下更新列表list
	 */
	public List<String> LIST_COL_UPDATED = null;
	
	/*
	 * 自定义的附属信息
	 */
	public Map<Object,Object> MAP_EXT_PROPERTY = null;
	
	/*
	 * 变更信息
	 */
	private StringBuilder _CHANGED_INFO = null;
	
	/*
	 * 分割行
	 */
	private static final String _SEPARATE_LINE = "************************************\r\n";
	

	/*
	 * 实际的表名
	 */
	public String CURRENT_TABLE_NAME = null;
	
	
	//属性定义区域
	
	
	/**
	 * 
	 */
	private long id = 0l;
	
	
	/**
	 * 
	 */
	private String usersay = "";
	
	
	/**
	 * 
	 */
	private String syscmd = "";
	
	
	/**
	 * 
	 */
	private String cmdcontent = "";
	
	
	/**
	 * 
	 */
	private String cmdp1 = "";
	
	
	/**
	 * 
	 */
	private String cmdp2 = "";
	
	
	/**
	 * 
	 */
	private String cmdp3 = "";
	
	
	/**
	 * 
	 */
	private String cmdp4 = "";
	
	
	/**
	 * 
	 */
	private String cmdp5 = "";
	
	
	/**
	 * 
	 */
	private java.util.Date createtime = null;
	
	
	/**
	 * 
	 */
	private int status = 0;
	
	
	/**
	 * 设置附加属性
	 */
	public void SET_EXT_PROPERTY(Object key,Object value){
		if (MAP_EXT_PROPERTY==null)
			MAP_EXT_PROPERTY = new LinkedHashMap<Object,Object>();
		MAP_EXT_PROPERTY.put(key,value);
	}
	
	/**
	 * 获得附加属性
	 */
	public Object GET_EXT_PROPERTY(Object key){
		if (MAP_EXT_PROPERTY!=null)
			return MAP_EXT_PROPERTY.get(key);
		else
			return null;
	}
	
	/**
	 * 获得附加属性MAP
	 */
	public Map<Object,Object> GET_EXT_PROPERTY_MAP(){
		return MAP_EXT_PROPERTY;
	}
	
	/**
	 * 获得更改的字段列表.
	 */
	public List<String> GET_UPDATED_COL_LIST(){
		return LIST_COL_UPDATED;
	}
	
	/**
	 * 得到_CHANGED_INFO
	 */
	public String GET_CHANGED_INFO(){
		if (this._CHANGED_INFO==null){
			return null;
		}else{
			this._CHANGED_INFO.append(_SEPARATE_LINE);
			return this._CHANGED_INFO.toString(); 
		}
	}
	
	
	/**
	 * 获取数值
	 */
	public long getId()
	{
		return this.id;
	}
	
	/**
	 * 获取数值
	 */
	public String getUsersay()
	{
		return this.usersay;
	}
	
	/**
	 * 获取数值
	 */
	public String getSyscmd()
	{
		return this.syscmd;
	}
	
	/**
	 * 获取数值
	 */
	public String getCmdcontent()
	{
		return this.cmdcontent;
	}
	
	/**
	 * 获取数值
	 */
	public String getCmdp1()
	{
		return this.cmdp1;
	}
	
	/**
	 * 获取数值
	 */
	public String getCmdp2()
	{
		return this.cmdp2;
	}
	
	/**
	 * 获取数值
	 */
	public String getCmdp3()
	{
		return this.cmdp3;
	}
	
	/**
	 * 获取数值
	 */
	public String getCmdp4()
	{
		return this.cmdp4;
	}
	
	/**
	 * 获取数值
	 */
	public String getCmdp5()
	{
		return this.cmdp5;
	}
	
	/**
	 * 获取数值
	 */
	public java.util.Date getCreatetime()
	{
		return this.createtime;
	}
	
	/**
	 * 获取数值
	 */
	public int getStatus()
	{
		return this.status;
	}
	

	
	/**
	 * 初始化set相关的信息
	 */
	private void initSetInfo(){
			this.LIST_COL_UPDATED = new ArrayList<String>();
			this._CHANGED_INFO = new StringBuilder(_SEPARATE_LINE+"表NgnSay，主键\""+this.id+"\"变更信息为:\r\n");
	}

	
	/**
	 * 设置数值
	 */
	public void setId(long id)
	{
		if (this.id!=id){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("id")){ 
				this.LIST_COL_UPDATED.add("id");
			}
			this._CHANGED_INFO.append("字段id由\""+this.id+"\"修改为\""+id+"\"\r\n");
			this.id = id;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setUsersay(String usersay)
	{
		if ((!String.valueOf(this.usersay).equals(String.valueOf(usersay)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("usersay")){ 
				this.LIST_COL_UPDATED.add("usersay");
			}
			this._CHANGED_INFO.append("字段usersay由\""+this.usersay+"\"修改为\""+usersay+"\"\r\n");
			this.usersay = usersay;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setSyscmd(String syscmd)
	{
		if ((!String.valueOf(this.syscmd).equals(String.valueOf(syscmd)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("syscmd")){ 
				this.LIST_COL_UPDATED.add("syscmd");
			}
			this._CHANGED_INFO.append("字段syscmd由\""+this.syscmd+"\"修改为\""+syscmd+"\"\r\n");
			this.syscmd = syscmd;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCmdcontent(String cmdcontent)
	{
		if ((!String.valueOf(this.cmdcontent).equals(String.valueOf(cmdcontent)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("cmdcontent")){ 
				this.LIST_COL_UPDATED.add("cmdcontent");
			}
			this._CHANGED_INFO.append("字段cmdcontent由\""+this.cmdcontent+"\"修改为\""+cmdcontent+"\"\r\n");
			this.cmdcontent = cmdcontent;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCmdp1(String cmdp1)
	{
		if ((!String.valueOf(this.cmdp1).equals(String.valueOf(cmdp1)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("cmdp1")){ 
				this.LIST_COL_UPDATED.add("cmdp1");
			}
			this._CHANGED_INFO.append("字段cmdp1由\""+this.cmdp1+"\"修改为\""+cmdp1+"\"\r\n");
			this.cmdp1 = cmdp1;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCmdp2(String cmdp2)
	{
		if ((!String.valueOf(this.cmdp2).equals(String.valueOf(cmdp2)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("cmdp2")){ 
				this.LIST_COL_UPDATED.add("cmdp2");
			}
			this._CHANGED_INFO.append("字段cmdp2由\""+this.cmdp2+"\"修改为\""+cmdp2+"\"\r\n");
			this.cmdp2 = cmdp2;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCmdp3(String cmdp3)
	{
		if ((!String.valueOf(this.cmdp3).equals(String.valueOf(cmdp3)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("cmdp3")){ 
				this.LIST_COL_UPDATED.add("cmdp3");
			}
			this._CHANGED_INFO.append("字段cmdp3由\""+this.cmdp3+"\"修改为\""+cmdp3+"\"\r\n");
			this.cmdp3 = cmdp3;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCmdp4(String cmdp4)
	{
		if ((!String.valueOf(this.cmdp4).equals(String.valueOf(cmdp4)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("cmdp4")){ 
				this.LIST_COL_UPDATED.add("cmdp4");
			}
			this._CHANGED_INFO.append("字段cmdp4由\""+this.cmdp4+"\"修改为\""+cmdp4+"\"\r\n");
			this.cmdp4 = cmdp4;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCmdp5(String cmdp5)
	{
		if ((!String.valueOf(this.cmdp5).equals(String.valueOf(cmdp5)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("cmdp5")){ 
				this.LIST_COL_UPDATED.add("cmdp5");
			}
			this._CHANGED_INFO.append("字段cmdp5由\""+this.cmdp5+"\"修改为\""+cmdp5+"\"\r\n");
			this.cmdp5 = cmdp5;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCreatetime(java.util.Date createtime)
	{
		if ((this.createtime!=null&&createtime!=null&&!this.createtime.equals(createtime))||(this.createtime!=createtime)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("createtime")){ 
				this.LIST_COL_UPDATED.add("createtime");
			}
			this._CHANGED_INFO.append("字段createtime由\""+this.createtime+"\"修改为\""+createtime+"\"\r\n");
			this.createtime = createtime;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setStatus(int status)
	{
		if (this.status!=status){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("status")){ 
				this.LIST_COL_UPDATED.add("status");
			}
			this._CHANGED_INFO.append("字段status由\""+this.status+"\"修改为\""+status+"\"\r\n");
			this.status = status;
		}
	}
	
	

	/**
	 * 构造器
	 */
	public NgnSay(long id,String usersay,String syscmd,String cmdcontent,String cmdp1,String cmdp2,String cmdp3,String cmdp4,String cmdp5,java.util.Date createtime,int status){
	
		this.id = id;
		this.usersay = usersay;
		this.syscmd = syscmd;
		this.cmdcontent = cmdcontent;
		this.cmdp1 = cmdp1;
		this.cmdp2 = cmdp2;
		this.cmdp3 = cmdp3;
		this.cmdp4 = cmdp4;
		this.cmdp5 = cmdp5;
		this.createtime = createtime;
		this.status = status;
		
	}
	
	/**
	 * 构造器
	 */
	public NgnSay(){
	}
	

	
	/**
	 * 重载toString方法
	 */
	public String toString(){
		StringBuilder sb = new StringBuilder(_SEPARATE_LINE+"表NgnSay，主键\""+this.id+"\"的全部信息为:\r\n");
		sb.append("字段id数值为:"+id+"\r\n");
		sb.append("字段usersay数值为:"+usersay+"\r\n");
		sb.append("字段syscmd数值为:"+syscmd+"\r\n");
		sb.append("字段cmdcontent数值为:"+cmdcontent+"\r\n");
		sb.append("字段cmdp1数值为:"+cmdp1+"\r\n");
		sb.append("字段cmdp2数值为:"+cmdp2+"\r\n");
		sb.append("字段cmdp3数值为:"+cmdp3+"\r\n");
		sb.append("字段cmdp4数值为:"+cmdp4+"\r\n");
		sb.append("字段cmdp5数值为:"+cmdp5+"\r\n");
		sb.append("字段createtime数值为:"+createtime+"\r\n");
		sb.append("字段status数值为:"+status+"\r\n");
		
		sb.append(_SEPARATE_LINE);
		return sb.toString();
	}

	/**
	* 克隆自身
	* @return<a name=""></a>
	*/
	public Object clone(){
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {}
		return o;
	}

	
}