
 //Generated By XCodeFactory
package org.guihuotv.search.web.pojo;

import uw.dm.util.*;
import java.util.*;
import java.io.Serializable;

/**
 * Title: Base table NgnTimer的pojo类
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为ValueObject类，通过数据库表映像。
 */
public class NgnTimer implements Serializable,Cloneable {

	private static final long serialVersionUID = 1L;
	
	/*
	 * 字段，类型map表
	 */
	public static final HashMap<String, Integer> MAP_COL_TYPE = new HashMap<String, Integer>();
	
	/*
	 * 原始名称，属性名称map表
	 */
	public static final HashMap<String, String> MAP_COL_NAME = new HashMap<String, String>();
	
	 
	static{
		
		MAP_COL_TYPE.put("id",DmObjectType.LONG);
		MAP_COL_NAME.put("id","id");
		
		MAP_COL_TYPE.put("name",DmObjectType.STRING);
		MAP_COL_NAME.put("name","name");
		
		MAP_COL_TYPE.put("timertype",DmObjectType.INT);
		MAP_COL_NAME.put("timertype","timertype");
		
		MAP_COL_TYPE.put("timer",DmObjectType.DATE);
		MAP_COL_NAME.put("timer","timer");
		
		MAP_COL_TYPE.put("timerurl",DmObjectType.STRING);
		MAP_COL_NAME.put("timerurl","timerurl");
		
		MAP_COL_TYPE.put("p1",DmObjectType.STRING);
		MAP_COL_NAME.put("p1","p1");
		
		MAP_COL_TYPE.put("p2",DmObjectType.STRING);
		MAP_COL_NAME.put("p2","p2");
		
		MAP_COL_TYPE.put("p3",DmObjectType.STRING);
		MAP_COL_NAME.put("p3","p3");
		
		MAP_COL_TYPE.put("createtime",DmObjectType.DATE);
		MAP_COL_NAME.put("createtime","createtime");
		
		MAP_COL_TYPE.put("status",DmObjectType.INT);
		MAP_COL_NAME.put("status","status");
		
	}

	public static final String TABLE_NAME = "ngn_timer";
	
	
	public static final String COL_ID = "id";
	
	public static final String COL_NAME = "name";
	
	public static final String COL_TIMERTYPE = "timertype";
	
	public static final String COL_TIMER = "timer";
	
	public static final String COL_TIMERURL = "timerurl";
	
	public static final String COL_P1 = "p1";
	
	public static final String COL_P2 = "p2";
	
	public static final String COL_P3 = "p3";
	
	public static final String COL_CREATETIME = "createtime";
	
	public static final String COL_STATUS = "status";
	

	/*
	 * 轻量级状态下更新列表list
	 */
	public List<String> LIST_COL_UPDATED = null;
	
	/*
	 * 自定义的附属信息
	 */
	public Map<Object,Object> MAP_EXT_PROPERTY = null;
	
	/*
	 * 变更信息
	 */
	private StringBuilder _CHANGED_INFO = null;
	
	/*
	 * 分割行
	 */
	private static final String _SEPARATE_LINE = "************************************\r\n";
	

	/*
	 * 实际的表名
	 */
	public String CURRENT_TABLE_NAME = null;
	
	
	//属性定义区域
	
	
	/**
	 * 
	 */
	private long id = 0l;
	
	
	/**
	 * 
	 */
	private String name = "";
	
	
	/**
	 * 
	 */
	private int timertype = 0;
	
	
	/**
	 * 
	 */
	private java.util.Date timer = null;
	
	
	/**
	 * 
	 */
	private String timerurl = "";
	
	
	/**
	 * 
	 */
	private String p1 = "";
	
	
	/**
	 * 
	 */
	private String p2 = "";
	
	
	/**
	 * 
	 */
	private String p3 = "";
	
	
	/**
	 * 
	 */
	private java.util.Date createtime = null;
	
	
	/**
	 * 
	 */
	private int status = 0;
	
	
	/**
	 * 设置附加属性
	 */
	public void SET_EXT_PROPERTY(Object key,Object value){
		if (MAP_EXT_PROPERTY==null)
			MAP_EXT_PROPERTY = new LinkedHashMap<Object,Object>();
		MAP_EXT_PROPERTY.put(key,value);
	}
	
	/**
	 * 获得附加属性
	 */
	public Object GET_EXT_PROPERTY(Object key){
		if (MAP_EXT_PROPERTY!=null)
			return MAP_EXT_PROPERTY.get(key);
		else
			return null;
	}
	
	/**
	 * 获得附加属性MAP
	 */
	public Map<Object,Object> GET_EXT_PROPERTY_MAP(){
		return MAP_EXT_PROPERTY;
	}
	
	/**
	 * 获得更改的字段列表.
	 */
	public List<String> GET_UPDATED_COL_LIST(){
		return LIST_COL_UPDATED;
	}
	
	/**
	 * 得到_CHANGED_INFO
	 */
	public String GET_CHANGED_INFO(){
		if (this._CHANGED_INFO==null){
			return null;
		}else{
			this._CHANGED_INFO.append(_SEPARATE_LINE);
			return this._CHANGED_INFO.toString(); 
		}
	}
	
	
	/**
	 * 获取数值
	 */
	public long getId()
	{
		return this.id;
	}
	
	/**
	 * 获取数值
	 */
	public String getName()
	{
		return this.name;
	}
	
	/**
	 * 获取数值
	 */
	public int getTimertype()
	{
		return this.timertype;
	}
	
	/**
	 * 获取数值
	 */
	public java.util.Date getTimer()
	{
		return this.timer;
	}
	
	/**
	 * 获取数值
	 */
	public String getTimerurl()
	{
		return this.timerurl;
	}
	
	/**
	 * 获取数值
	 */
	public String getP1()
	{
		return this.p1;
	}
	
	/**
	 * 获取数值
	 */
	public String getP2()
	{
		return this.p2;
	}
	
	/**
	 * 获取数值
	 */
	public String getP3()
	{
		return this.p3;
	}
	
	/**
	 * 获取数值
	 */
	public java.util.Date getCreatetime()
	{
		return this.createtime;
	}
	
	/**
	 * 获取数值
	 */
	public int getStatus()
	{
		return this.status;
	}
	

	
	/**
	 * 初始化set相关的信息
	 */
	private void initSetInfo(){
			this.LIST_COL_UPDATED = new ArrayList<String>();
			this._CHANGED_INFO = new StringBuilder(_SEPARATE_LINE+"表NgnTimer，主键\""+this.id+"\"变更信息为:\r\n");
	}

	
	/**
	 * 设置数值
	 */
	public void setId(long id)
	{
		if (this.id!=id){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("id")){ 
				this.LIST_COL_UPDATED.add("id");
			}
			this._CHANGED_INFO.append("字段id由\""+this.id+"\"修改为\""+id+"\"\r\n");
			this.id = id;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setName(String name)
	{
		if ((!String.valueOf(this.name).equals(String.valueOf(name)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("name")){ 
				this.LIST_COL_UPDATED.add("name");
			}
			this._CHANGED_INFO.append("字段name由\""+this.name+"\"修改为\""+name+"\"\r\n");
			this.name = name;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setTimertype(int timertype)
	{
		if (this.timertype!=timertype){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("timertype")){ 
				this.LIST_COL_UPDATED.add("timertype");
			}
			this._CHANGED_INFO.append("字段timertype由\""+this.timertype+"\"修改为\""+timertype+"\"\r\n");
			this.timertype = timertype;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setTimer(java.util.Date timer)
	{
		if ((this.timer!=null&&timer!=null&&!this.timer.equals(timer))||(this.timer!=timer)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("timer")){ 
				this.LIST_COL_UPDATED.add("timer");
			}
			this._CHANGED_INFO.append("字段timer由\""+this.timer+"\"修改为\""+timer+"\"\r\n");
			this.timer = timer;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setTimerurl(String timerurl)
	{
		if ((!String.valueOf(this.timerurl).equals(String.valueOf(timerurl)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("timerurl")){ 
				this.LIST_COL_UPDATED.add("timerurl");
			}
			this._CHANGED_INFO.append("字段timerurl由\""+this.timerurl+"\"修改为\""+timerurl+"\"\r\n");
			this.timerurl = timerurl;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setP1(String p1)
	{
		if ((!String.valueOf(this.p1).equals(String.valueOf(p1)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("p1")){ 
				this.LIST_COL_UPDATED.add("p1");
			}
			this._CHANGED_INFO.append("字段p1由\""+this.p1+"\"修改为\""+p1+"\"\r\n");
			this.p1 = p1;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setP2(String p2)
	{
		if ((!String.valueOf(this.p2).equals(String.valueOf(p2)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("p2")){ 
				this.LIST_COL_UPDATED.add("p2");
			}
			this._CHANGED_INFO.append("字段p2由\""+this.p2+"\"修改为\""+p2+"\"\r\n");
			this.p2 = p2;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setP3(String p3)
	{
		if ((!String.valueOf(this.p3).equals(String.valueOf(p3)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("p3")){ 
				this.LIST_COL_UPDATED.add("p3");
			}
			this._CHANGED_INFO.append("字段p3由\""+this.p3+"\"修改为\""+p3+"\"\r\n");
			this.p3 = p3;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCreatetime(java.util.Date createtime)
	{
		if ((this.createtime!=null&&createtime!=null&&!this.createtime.equals(createtime))||(this.createtime!=createtime)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("createtime")){ 
				this.LIST_COL_UPDATED.add("createtime");
			}
			this._CHANGED_INFO.append("字段createtime由\""+this.createtime+"\"修改为\""+createtime+"\"\r\n");
			this.createtime = createtime;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setStatus(int status)
	{
		if (this.status!=status){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("status")){ 
				this.LIST_COL_UPDATED.add("status");
			}
			this._CHANGED_INFO.append("字段status由\""+this.status+"\"修改为\""+status+"\"\r\n");
			this.status = status;
		}
	}
	
	

	/**
	 * 构造器
	 */
	public NgnTimer(long id,String name,int timertype,java.util.Date timer,String timerurl,String p1,String p2,String p3,java.util.Date createtime,int status){
	
		this.id = id;
		this.name = name;
		this.timertype = timertype;
		this.timer = timer;
		this.timerurl = timerurl;
		this.p1 = p1;
		this.p2 = p2;
		this.p3 = p3;
		this.createtime = createtime;
		this.status = status;
		
	}
	
	/**
	 * 构造器
	 */
	public NgnTimer(){
	}
	

	
	/**
	 * 重载toString方法
	 */
	public String toString(){
		StringBuilder sb = new StringBuilder(_SEPARATE_LINE+"表NgnTimer，主键\""+this.id+"\"的全部信息为:\r\n");
		sb.append("字段id数值为:"+id+"\r\n");
		sb.append("字段name数值为:"+name+"\r\n");
		sb.append("字段timertype数值为:"+timertype+"\r\n");
		sb.append("字段timer数值为:"+timer+"\r\n");
		sb.append("字段timerurl数值为:"+timerurl+"\r\n");
		sb.append("字段p1数值为:"+p1+"\r\n");
		sb.append("字段p2数值为:"+p2+"\r\n");
		sb.append("字段p3数值为:"+p3+"\r\n");
		sb.append("字段createtime数值为:"+createtime+"\r\n");
		sb.append("字段status数值为:"+status+"\r\n");
		
		sb.append(_SEPARATE_LINE);
		return sb.toString();
	}

	/**
	* 克隆自身
	* @return<a name=""></a>
	*/
	public Object clone(){
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {}
		return o;
	}

	
}