
 //Generated By XCodeFactory
package org.guihuotv.search.web.pojo;

import uw.dm.util.*;
import java.util.*;
import java.io.Serializable;

/**
 * Title: Base table NgnUser的pojo类
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为ValueObject类，通过数据库表映像。
 */
public class NgnUser implements Serializable,Cloneable {

	private static final long serialVersionUID = 1L;
	
	/*
	 * 字段，类型map表
	 */
	public static final HashMap<String, Integer> MAP_COL_TYPE = new HashMap<String, Integer>();
	
	/*
	 * 原始名称，属性名称map表
	 */
	public static final HashMap<String, String> MAP_COL_NAME = new HashMap<String, String>();
	
	 
	static{
		
		MAP_COL_TYPE.put("id",DmObjectType.LONG);
		MAP_COL_NAME.put("id","id");
		
		MAP_COL_TYPE.put("user_type",DmObjectType.INT);
		MAP_COL_NAME.put("user_type","userType");
		
		MAP_COL_TYPE.put("username",DmObjectType.STRING);
		MAP_COL_NAME.put("username","username");
		
		MAP_COL_TYPE.put("passwd",DmObjectType.STRING);
		MAP_COL_NAME.put("passwd","passwd");
		
		MAP_COL_TYPE.put("mobile",DmObjectType.STRING);
		MAP_COL_NAME.put("mobile","mobile");
		
		MAP_COL_TYPE.put("email",DmObjectType.STRING);
		MAP_COL_NAME.put("email","email");
		
		MAP_COL_TYPE.put("alias_name",DmObjectType.STRING);
		MAP_COL_NAME.put("alias_name","aliasName");
		
		MAP_COL_TYPE.put("birthday",DmObjectType.DATE);
		MAP_COL_NAME.put("birthday","birthday");
		
		MAP_COL_TYPE.put("age",DmObjectType.INT);
		MAP_COL_NAME.put("age","age");
		
		MAP_COL_TYPE.put("gender",DmObjectType.INT);
		MAP_COL_NAME.put("gender","gender");
		
		MAP_COL_TYPE.put("remark",DmObjectType.STRING);
		MAP_COL_NAME.put("remark","remark");
		
		MAP_COL_TYPE.put("school",DmObjectType.STRING);
		MAP_COL_NAME.put("school","school");
		
		MAP_COL_TYPE.put("company",DmObjectType.STRING);
		MAP_COL_NAME.put("company","company");
		
		MAP_COL_TYPE.put("occupation",DmObjectType.STRING);
		MAP_COL_NAME.put("occupation","occupation");
		
		MAP_COL_TYPE.put("industry",DmObjectType.STRING);
		MAP_COL_NAME.put("industry","industry");
		
		MAP_COL_TYPE.put("user_point",DmObjectType.INT);
		MAP_COL_NAME.put("user_point","userPoint");
		
		MAP_COL_TYPE.put("last_logon_date",DmObjectType.DATE);
		MAP_COL_NAME.put("last_logon_date","lastLogonDate");
		
		MAP_COL_TYPE.put("create_date",DmObjectType.DATE);
		MAP_COL_NAME.put("create_date","createDate");
		
		MAP_COL_TYPE.put("modify_date",DmObjectType.DATE);
		MAP_COL_NAME.put("modify_date","modifyDate");
		
		MAP_COL_TYPE.put("status",DmObjectType.INT);
		MAP_COL_NAME.put("status","status");
		
	}

	public static final String TABLE_NAME = "ngn_user";
	
	
	public static final String COL_ID = "id";
	
	public static final String COL_USER_TYPE = "user_type";
	
	public static final String COL_USERNAME = "username";
	
	public static final String COL_PASSWD = "passwd";
	
	public static final String COL_MOBILE = "mobile";
	
	public static final String COL_EMAIL = "email";
	
	public static final String COL_ALIAS_NAME = "alias_name";
	
	public static final String COL_BIRTHDAY = "birthday";
	
	public static final String COL_AGE = "age";
	
	public static final String COL_GENDER = "gender";
	
	public static final String COL_REMARK = "remark";
	
	public static final String COL_SCHOOL = "school";
	
	public static final String COL_COMPANY = "company";
	
	public static final String COL_OCCUPATION = "occupation";
	
	public static final String COL_INDUSTRY = "industry";
	
	public static final String COL_USER_POINT = "user_point";
	
	public static final String COL_LAST_LOGON_DATE = "last_logon_date";
	
	public static final String COL_CREATE_DATE = "create_date";
	
	public static final String COL_MODIFY_DATE = "modify_date";
	
	public static final String COL_STATUS = "status";
	

	/*
	 * 轻量级状态下更新列表list
	 */
	public List<String> LIST_COL_UPDATED = null;
	
	/*
	 * 自定义的附属信息
	 */
	public Map<Object,Object> MAP_EXT_PROPERTY = null;
	
	/*
	 * 变更信息
	 */
	private StringBuilder _CHANGED_INFO = null;
	
	/*
	 * 分割行
	 */
	private static final String _SEPARATE_LINE = "************************************\r\n";
	

	/*
	 * 实际的表名
	 */
	public String CURRENT_TABLE_NAME = null;
	
	
	//属性定义区域
	
	
	/**
	 * ID
	 */
	private long id = 0l;
	
	
	/**
	 * 用户类型，0VIP用户，1普通用户
	 */
	private int userType = 0;
	
	
	/**
	 * 用户名
	 */
	private String username = "";
	
	
	/**
	 * 密码
	 */
	private String passwd = "";
	
	
	/**
	 * 手机号码
	 */
	private String mobile = "";
	
	
	/**
	 * Email地址
	 */
	private String email = "";
	
	
	/**
	 * 昵称
	 */
	private String aliasName = "";
	
	
	/**
	 * 生日
	 */
	private java.util.Date birthday = null;
	
	
	/**
	 * 年龄
	 */
	private int age = 0;
	
	
	/**
	 * 性别(0女1男)
	 */
	private int gender = 0;
	
	
	/**
	 * 备注
	 */
	private String remark = "";
	
	
	/**
	 * 学校
	 */
	private String school = "";
	
	
	/**
	 * 公司
	 */
	private String company = "";
	
	
	/**
	 * 职业
	 */
	private String occupation = "";
	
	
	/**
	 * 行业
	 */
	private String industry = "";
	
	
	/**
	 * 用户积分
	 */
	private int userPoint = 0;
	
	
	/**
	 * 上次登录时间
	 */
	private java.util.Date lastLogonDate = null;
	
	
	/**
	 * 创建时间
	 */
	private java.util.Date createDate = null;
	
	
	/**
	 * 修改时间
	 */
	private java.util.Date modifyDate = null;
	
	
	/**
	 * 状态
	 */
	private int status = 0;
	
	
	/**
	 * 设置附加属性
	 */
	public void SET_EXT_PROPERTY(Object key,Object value){
		if (MAP_EXT_PROPERTY==null)
			MAP_EXT_PROPERTY = new LinkedHashMap<Object,Object>();
		MAP_EXT_PROPERTY.put(key,value);
	}
	
	/**
	 * 获得附加属性
	 */
	public Object GET_EXT_PROPERTY(Object key){
		if (MAP_EXT_PROPERTY!=null)
			return MAP_EXT_PROPERTY.get(key);
		else
			return null;
	}
	
	/**
	 * 获得附加属性MAP
	 */
	public Map<Object,Object> GET_EXT_PROPERTY_MAP(){
		return MAP_EXT_PROPERTY;
	}
	
	/**
	 * 获得更改的字段列表.
	 */
	public List<String> GET_UPDATED_COL_LIST(){
		return LIST_COL_UPDATED;
	}
	
	/**
	 * 得到_CHANGED_INFO
	 */
	public String GET_CHANGED_INFO(){
		if (this._CHANGED_INFO==null){
			return null;
		}else{
			this._CHANGED_INFO.append(_SEPARATE_LINE);
			return this._CHANGED_INFO.toString(); 
		}
	}
	
	
	/**
	 * 获取ID数值
	 */
	public long getId()
	{
		return this.id;
	}
	
	/**
	 * 获取用户类型，0VIP用户，1普通用户数值
	 */
	public int getUserType()
	{
		return this.userType;
	}
	
	/**
	 * 获取用户名数值
	 */
	public String getUsername()
	{
		return this.username;
	}
	
	/**
	 * 获取密码数值
	 */
	public String getPasswd()
	{
		return this.passwd;
	}
	
	/**
	 * 获取手机号码数值
	 */
	public String getMobile()
	{
		return this.mobile;
	}
	
	/**
	 * 获取Email地址数值
	 */
	public String getEmail()
	{
		return this.email;
	}
	
	/**
	 * 获取昵称数值
	 */
	public String getAliasName()
	{
		return this.aliasName;
	}
	
	/**
	 * 获取生日数值
	 */
	public java.util.Date getBirthday()
	{
		return this.birthday;
	}
	
	/**
	 * 获取年龄数值
	 */
	public int getAge()
	{
		return this.age;
	}
	
	/**
	 * 获取性别(0女1男)数值
	 */
	public int getGender()
	{
		return this.gender;
	}
	
	/**
	 * 获取备注数值
	 */
	public String getRemark()
	{
		return this.remark;
	}
	
	/**
	 * 获取学校数值
	 */
	public String getSchool()
	{
		return this.school;
	}
	
	/**
	 * 获取公司数值
	 */
	public String getCompany()
	{
		return this.company;
	}
	
	/**
	 * 获取职业数值
	 */
	public String getOccupation()
	{
		return this.occupation;
	}
	
	/**
	 * 获取行业数值
	 */
	public String getIndustry()
	{
		return this.industry;
	}
	
	/**
	 * 获取用户积分数值
	 */
	public int getUserPoint()
	{
		return this.userPoint;
	}
	
	/**
	 * 获取上次登录时间数值
	 */
	public java.util.Date getLastLogonDate()
	{
		return this.lastLogonDate;
	}
	
	/**
	 * 获取创建时间数值
	 */
	public java.util.Date getCreateDate()
	{
		return this.createDate;
	}
	
	/**
	 * 获取修改时间数值
	 */
	public java.util.Date getModifyDate()
	{
		return this.modifyDate;
	}
	
	/**
	 * 获取状态数值
	 */
	public int getStatus()
	{
		return this.status;
	}
	

	
	/**
	 * 初始化set相关的信息
	 */
	private void initSetInfo(){
			this.LIST_COL_UPDATED = new ArrayList<String>();
			this._CHANGED_INFO = new StringBuilder(_SEPARATE_LINE+"表NgnUser，主键\""+this.id+"\"变更信息为:\r\n");
	}

	
	/**
	 * 设置ID数值
	 */
	public void setId(long id)
	{
		if (this.id!=id){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("id")){ 
				this.LIST_COL_UPDATED.add("id");
			}
			this._CHANGED_INFO.append("字段id由\""+this.id+"\"修改为\""+id+"\"\r\n");
			this.id = id;
		}
	}
	
	/**
	 * 设置用户类型，0VIP用户，1普通用户数值
	 */
	public void setUserType(int userType)
	{
		if (this.userType!=userType){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("user_type")){ 
				this.LIST_COL_UPDATED.add("user_type");
			}
			this._CHANGED_INFO.append("字段user_type由\""+this.userType+"\"修改为\""+userType+"\"\r\n");
			this.userType = userType;
		}
	}
	
	/**
	 * 设置用户名数值
	 */
	public void setUsername(String username)
	{
		if ((!String.valueOf(this.username).equals(String.valueOf(username)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("username")){ 
				this.LIST_COL_UPDATED.add("username");
			}
			this._CHANGED_INFO.append("字段username由\""+this.username+"\"修改为\""+username+"\"\r\n");
			this.username = username;
		}
	}
	
	/**
	 * 设置密码数值
	 */
	public void setPasswd(String passwd)
	{
		if ((!String.valueOf(this.passwd).equals(String.valueOf(passwd)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("passwd")){ 
				this.LIST_COL_UPDATED.add("passwd");
			}
			this._CHANGED_INFO.append("字段passwd由\""+this.passwd+"\"修改为\""+passwd+"\"\r\n");
			this.passwd = passwd;
		}
	}
	
	/**
	 * 设置手机号码数值
	 */
	public void setMobile(String mobile)
	{
		if ((!String.valueOf(this.mobile).equals(String.valueOf(mobile)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("mobile")){ 
				this.LIST_COL_UPDATED.add("mobile");
			}
			this._CHANGED_INFO.append("字段mobile由\""+this.mobile+"\"修改为\""+mobile+"\"\r\n");
			this.mobile = mobile;
		}
	}
	
	/**
	 * 设置Email地址数值
	 */
	public void setEmail(String email)
	{
		if ((!String.valueOf(this.email).equals(String.valueOf(email)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("email")){ 
				this.LIST_COL_UPDATED.add("email");
			}
			this._CHANGED_INFO.append("字段email由\""+this.email+"\"修改为\""+email+"\"\r\n");
			this.email = email;
		}
	}
	
	/**
	 * 设置昵称数值
	 */
	public void setAliasName(String aliasName)
	{
		if ((!String.valueOf(this.aliasName).equals(String.valueOf(aliasName)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("alias_name")){ 
				this.LIST_COL_UPDATED.add("alias_name");
			}
			this._CHANGED_INFO.append("字段alias_name由\""+this.aliasName+"\"修改为\""+aliasName+"\"\r\n");
			this.aliasName = aliasName;
		}
	}
	
	/**
	 * 设置生日数值
	 */
	public void setBirthday(java.util.Date birthday)
	{
		if ((this.birthday!=null&&birthday!=null&&!this.birthday.equals(birthday))||(this.birthday!=birthday)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("birthday")){ 
				this.LIST_COL_UPDATED.add("birthday");
			}
			this._CHANGED_INFO.append("字段birthday由\""+this.birthday+"\"修改为\""+birthday+"\"\r\n");
			this.birthday = birthday;
		}
	}
	
	/**
	 * 设置年龄数值
	 */
	public void setAge(int age)
	{
		if (this.age!=age){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("age")){ 
				this.LIST_COL_UPDATED.add("age");
			}
			this._CHANGED_INFO.append("字段age由\""+this.age+"\"修改为\""+age+"\"\r\n");
			this.age = age;
		}
	}
	
	/**
	 * 设置性别(0女1男)数值
	 */
	public void setGender(int gender)
	{
		if (this.gender!=gender){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("gender")){ 
				this.LIST_COL_UPDATED.add("gender");
			}
			this._CHANGED_INFO.append("字段gender由\""+this.gender+"\"修改为\""+gender+"\"\r\n");
			this.gender = gender;
		}
	}
	
	/**
	 * 设置备注数值
	 */
	public void setRemark(String remark)
	{
		if ((!String.valueOf(this.remark).equals(String.valueOf(remark)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("remark")){ 
				this.LIST_COL_UPDATED.add("remark");
			}
			this._CHANGED_INFO.append("字段remark由\""+this.remark+"\"修改为\""+remark+"\"\r\n");
			this.remark = remark;
		}
	}
	
	/**
	 * 设置学校数值
	 */
	public void setSchool(String school)
	{
		if ((!String.valueOf(this.school).equals(String.valueOf(school)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("school")){ 
				this.LIST_COL_UPDATED.add("school");
			}
			this._CHANGED_INFO.append("字段school由\""+this.school+"\"修改为\""+school+"\"\r\n");
			this.school = school;
		}
	}
	
	/**
	 * 设置公司数值
	 */
	public void setCompany(String company)
	{
		if ((!String.valueOf(this.company).equals(String.valueOf(company)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("company")){ 
				this.LIST_COL_UPDATED.add("company");
			}
			this._CHANGED_INFO.append("字段company由\""+this.company+"\"修改为\""+company+"\"\r\n");
			this.company = company;
		}
	}
	
	/**
	 * 设置职业数值
	 */
	public void setOccupation(String occupation)
	{
		if ((!String.valueOf(this.occupation).equals(String.valueOf(occupation)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("occupation")){ 
				this.LIST_COL_UPDATED.add("occupation");
			}
			this._CHANGED_INFO.append("字段occupation由\""+this.occupation+"\"修改为\""+occupation+"\"\r\n");
			this.occupation = occupation;
		}
	}
	
	/**
	 * 设置行业数值
	 */
	public void setIndustry(String industry)
	{
		if ((!String.valueOf(this.industry).equals(String.valueOf(industry)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("industry")){ 
				this.LIST_COL_UPDATED.add("industry");
			}
			this._CHANGED_INFO.append("字段industry由\""+this.industry+"\"修改为\""+industry+"\"\r\n");
			this.industry = industry;
		}
	}
	
	/**
	 * 设置用户积分数值
	 */
	public void setUserPoint(int userPoint)
	{
		if (this.userPoint!=userPoint){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("user_point")){ 
				this.LIST_COL_UPDATED.add("user_point");
			}
			this._CHANGED_INFO.append("字段user_point由\""+this.userPoint+"\"修改为\""+userPoint+"\"\r\n");
			this.userPoint = userPoint;
		}
	}
	
	/**
	 * 设置上次登录时间数值
	 */
	public void setLastLogonDate(java.util.Date lastLogonDate)
	{
		if ((this.lastLogonDate!=null&&lastLogonDate!=null&&!this.lastLogonDate.equals(lastLogonDate))||(this.lastLogonDate!=lastLogonDate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("last_logon_date")){ 
				this.LIST_COL_UPDATED.add("last_logon_date");
			}
			this._CHANGED_INFO.append("字段last_logon_date由\""+this.lastLogonDate+"\"修改为\""+lastLogonDate+"\"\r\n");
			this.lastLogonDate = lastLogonDate;
		}
	}
	
	/**
	 * 设置创建时间数值
	 */
	public void setCreateDate(java.util.Date createDate)
	{
		if ((this.createDate!=null&&createDate!=null&&!this.createDate.equals(createDate))||(this.createDate!=createDate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("create_date")){ 
				this.LIST_COL_UPDATED.add("create_date");
			}
			this._CHANGED_INFO.append("字段create_date由\""+this.createDate+"\"修改为\""+createDate+"\"\r\n");
			this.createDate = createDate;
		}
	}
	
	/**
	 * 设置修改时间数值
	 */
	public void setModifyDate(java.util.Date modifyDate)
	{
		if ((this.modifyDate!=null&&modifyDate!=null&&!this.modifyDate.equals(modifyDate))||(this.modifyDate!=modifyDate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("modify_date")){ 
				this.LIST_COL_UPDATED.add("modify_date");
			}
			this._CHANGED_INFO.append("字段modify_date由\""+this.modifyDate+"\"修改为\""+modifyDate+"\"\r\n");
			this.modifyDate = modifyDate;
		}
	}
	
	/**
	 * 设置状态数值
	 */
	public void setStatus(int status)
	{
		if (this.status!=status){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("status")){ 
				this.LIST_COL_UPDATED.add("status");
			}
			this._CHANGED_INFO.append("字段status由\""+this.status+"\"修改为\""+status+"\"\r\n");
			this.status = status;
		}
	}
	
	

	/**
	 * 构造器
	 */
	public NgnUser(long id,int userType,String username,String passwd,String mobile,String email,String aliasName,java.util.Date birthday,int age,int gender,String remark,String school,String company,String occupation,String industry,int userPoint,java.util.Date lastLogonDate,java.util.Date createDate,java.util.Date modifyDate,int status){
	
		this.id = id;
		this.userType = userType;
		this.username = username;
		this.passwd = passwd;
		this.mobile = mobile;
		this.email = email;
		this.aliasName = aliasName;
		this.birthday = birthday;
		this.age = age;
		this.gender = gender;
		this.remark = remark;
		this.school = school;
		this.company = company;
		this.occupation = occupation;
		this.industry = industry;
		this.userPoint = userPoint;
		this.lastLogonDate = lastLogonDate;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.status = status;
		
	}
	
	/**
	 * 构造器
	 */
	public NgnUser(){
	}
	

	
	/**
	 * 重载toString方法
	 */
	public String toString(){
		StringBuilder sb = new StringBuilder(_SEPARATE_LINE+"表NgnUser，主键\""+this.id+"\"的全部信息为:\r\n");
		sb.append("字段id数值为:"+id+"\r\n");
		sb.append("字段user_type数值为:"+userType+"\r\n");
		sb.append("字段username数值为:"+username+"\r\n");
		sb.append("字段passwd数值为:"+passwd+"\r\n");
		sb.append("字段mobile数值为:"+mobile+"\r\n");
		sb.append("字段email数值为:"+email+"\r\n");
		sb.append("字段alias_name数值为:"+aliasName+"\r\n");
		sb.append("字段birthday数值为:"+birthday+"\r\n");
		sb.append("字段age数值为:"+age+"\r\n");
		sb.append("字段gender数值为:"+gender+"\r\n");
		sb.append("字段remark数值为:"+remark+"\r\n");
		sb.append("字段school数值为:"+school+"\r\n");
		sb.append("字段company数值为:"+company+"\r\n");
		sb.append("字段occupation数值为:"+occupation+"\r\n");
		sb.append("字段industry数值为:"+industry+"\r\n");
		sb.append("字段user_point数值为:"+userPoint+"\r\n");
		sb.append("字段last_logon_date数值为:"+lastLogonDate+"\r\n");
		sb.append("字段create_date数值为:"+createDate+"\r\n");
		sb.append("字段modify_date数值为:"+modifyDate+"\r\n");
		sb.append("字段status数值为:"+status+"\r\n");
		
		sb.append(_SEPARATE_LINE);
		return sb.toString();
	}

	/**
	* 克隆自身
	* @return<a name=""></a>
	*/
	public Object clone(){
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {}
		return o;
	}

	
}