
 //Generated By XCodeFactory
package org.guihuotv.search.web.pojo;

import uw.dm.util.*;
import java.util.*;
import java.io.Serializable;

/**
 * Title: Base table SysActionLog的pojo类
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为ValueObject类，通过数据库表映像。
 */
public class SysActionLog implements Serializable,Cloneable {

	private static final long serialVersionUID = 1L;
	
	/*
	 * 字段，类型map表
	 */
	public static final HashMap<String, Integer> MAP_COL_TYPE = new HashMap<String, Integer>();
	
	/*
	 * 原始名称，属性名称map表
	 */
	public static final HashMap<String, String> MAP_COL_NAME = new HashMap<String, String>();
	
	 
	static{
		
		MAP_COL_TYPE.put("id",DmObjectType.LONG);
		MAP_COL_NAME.put("id","id");
		
		MAP_COL_TYPE.put("user_id",DmObjectType.LONG);
		MAP_COL_NAME.put("user_id","userId");
		
		MAP_COL_TYPE.put("action_type",DmObjectType.INT);
		MAP_COL_NAME.put("action_type","actionType");
		
		MAP_COL_TYPE.put("action_module",DmObjectType.STRING);
		MAP_COL_NAME.put("action_module","actionModule");
		
		MAP_COL_TYPE.put("action_command",DmObjectType.STRING);
		MAP_COL_NAME.put("action_command","actionCommand");
		
		MAP_COL_TYPE.put("action_body",DmObjectType.STRING);
		MAP_COL_NAME.put("action_body","actionBody");
		
		MAP_COL_TYPE.put("action_ip",DmObjectType.STRING);
		MAP_COL_NAME.put("action_ip","actionIp");
		
		MAP_COL_TYPE.put("action_date",DmObjectType.DATE);
		MAP_COL_NAME.put("action_date","actionDate");
		
	}

	public static final String TABLE_NAME = "sys_action_log";
	
	
	public static final String COL_ID = "id";
	
	public static final String COL_USER_ID = "user_id";
	
	public static final String COL_ACTION_TYPE = "action_type";
	
	public static final String COL_ACTION_MODULE = "action_module";
	
	public static final String COL_ACTION_COMMAND = "action_command";
	
	public static final String COL_ACTION_BODY = "action_body";
	
	public static final String COL_ACTION_IP = "action_ip";
	
	public static final String COL_ACTION_DATE = "action_date";
	

	/*
	 * 轻量级状态下更新列表list
	 */
	public List<String> LIST_COL_UPDATED = null;
	
	/*
	 * 自定义的附属信息
	 */
	public Map<Object,Object> MAP_EXT_PROPERTY = null;
	
	/*
	 * 变更信息
	 */
	private StringBuilder _CHANGED_INFO = null;
	
	/*
	 * 分割行
	 */
	private static final String _SEPARATE_LINE = "************************************\r\n";
	

	/*
	 * 实际的表名
	 */
	public String CURRENT_TABLE_NAME = null;
	
	
	//属性定义区域
	
	
	/**
	 * 
	 */
	private long id = 0l;
	
	
	/**
	 * 操作的用户
	 */
	private long userId = 0l;
	
	
	/**
	 * 操作类型。1.访问日志 2.操作日志
	 */
	private int actionType = 0;
	
	
	/**
	 * 操作的模块
	 */
	private String actionModule = "";
	
	
	/**
	 * 操作的指令
	 */
	private String actionCommand = "";
	
	
	/**
	 * 操作的内容
	 */
	private String actionBody = "";
	
	
	/**
	 * 操作的IP
	 */
	private String actionIp = "";
	
	
	/**
	 * 操作的日期
	 */
	private java.util.Date actionDate = null;
	
	
	/**
	 * 设置附加属性
	 */
	public void SET_EXT_PROPERTY(Object key,Object value){
		if (MAP_EXT_PROPERTY==null)
			MAP_EXT_PROPERTY = new LinkedHashMap<Object,Object>();
		MAP_EXT_PROPERTY.put(key,value);
	}
	
	/**
	 * 获得附加属性
	 */
	public Object GET_EXT_PROPERTY(Object key){
		if (MAP_EXT_PROPERTY!=null)
			return MAP_EXT_PROPERTY.get(key);
		else
			return null;
	}
	
	/**
	 * 获得附加属性MAP
	 */
	public Map<Object,Object> GET_EXT_PROPERTY_MAP(){
		return MAP_EXT_PROPERTY;
	}
	
	/**
	 * 获得更改的字段列表.
	 */
	public List<String> GET_UPDATED_COL_LIST(){
		return LIST_COL_UPDATED;
	}
	
	/**
	 * 得到_CHANGED_INFO
	 */
	public String GET_CHANGED_INFO(){
		if (this._CHANGED_INFO==null){
			return null;
		}else{
			this._CHANGED_INFO.append(_SEPARATE_LINE);
			return this._CHANGED_INFO.toString(); 
		}
	}
	
	
	/**
	 * 获取数值
	 */
	public long getId()
	{
		return this.id;
	}
	
	/**
	 * 获取操作的用户数值
	 */
	public long getUserId()
	{
		return this.userId;
	}
	
	/**
	 * 获取操作类型。1.访问日志 2.操作日志数值
	 */
	public int getActionType()
	{
		return this.actionType;
	}
	
	/**
	 * 获取操作的模块数值
	 */
	public String getActionModule()
	{
		return this.actionModule;
	}
	
	/**
	 * 获取操作的指令数值
	 */
	public String getActionCommand()
	{
		return this.actionCommand;
	}
	
	/**
	 * 获取操作的内容数值
	 */
	public String getActionBody()
	{
		return this.actionBody;
	}
	
	/**
	 * 获取操作的IP数值
	 */
	public String getActionIp()
	{
		return this.actionIp;
	}
	
	/**
	 * 获取操作的日期数值
	 */
	public java.util.Date getActionDate()
	{
		return this.actionDate;
	}
	

	
	/**
	 * 初始化set相关的信息
	 */
	private void initSetInfo(){
			this.LIST_COL_UPDATED = new ArrayList<String>();
			this._CHANGED_INFO = new StringBuilder(_SEPARATE_LINE+"表SysActionLog，主键\""+this.id+"\"变更信息为:\r\n");
	}

	
	/**
	 * 设置数值
	 */
	public void setId(long id)
	{
		if (this.id!=id){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("id")){ 
				this.LIST_COL_UPDATED.add("id");
			}
			this._CHANGED_INFO.append("字段id由\""+this.id+"\"修改为\""+id+"\"\r\n");
			this.id = id;
		}
	}
	
	/**
	 * 设置操作的用户数值
	 */
	public void setUserId(long userId)
	{
		if (this.userId!=userId){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("user_id")){ 
				this.LIST_COL_UPDATED.add("user_id");
			}
			this._CHANGED_INFO.append("字段user_id由\""+this.userId+"\"修改为\""+userId+"\"\r\n");
			this.userId = userId;
		}
	}
	
	/**
	 * 设置操作类型。1.访问日志 2.操作日志数值
	 */
	public void setActionType(int actionType)
	{
		if (this.actionType!=actionType){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("action_type")){ 
				this.LIST_COL_UPDATED.add("action_type");
			}
			this._CHANGED_INFO.append("字段action_type由\""+this.actionType+"\"修改为\""+actionType+"\"\r\n");
			this.actionType = actionType;
		}
	}
	
	/**
	 * 设置操作的模块数值
	 */
	public void setActionModule(String actionModule)
	{
		if ((!String.valueOf(this.actionModule).equals(String.valueOf(actionModule)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("action_module")){ 
				this.LIST_COL_UPDATED.add("action_module");
			}
			this._CHANGED_INFO.append("字段action_module由\""+this.actionModule+"\"修改为\""+actionModule+"\"\r\n");
			this.actionModule = actionModule;
		}
	}
	
	/**
	 * 设置操作的指令数值
	 */
	public void setActionCommand(String actionCommand)
	{
		if ((!String.valueOf(this.actionCommand).equals(String.valueOf(actionCommand)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("action_command")){ 
				this.LIST_COL_UPDATED.add("action_command");
			}
			this._CHANGED_INFO.append("字段action_command由\""+this.actionCommand+"\"修改为\""+actionCommand+"\"\r\n");
			this.actionCommand = actionCommand;
		}
	}
	
	/**
	 * 设置操作的内容数值
	 */
	public void setActionBody(String actionBody)
	{
		if ((!String.valueOf(this.actionBody).equals(String.valueOf(actionBody)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("action_body")){ 
				this.LIST_COL_UPDATED.add("action_body");
			}
			this._CHANGED_INFO.append("字段action_body由\""+this.actionBody+"\"修改为\""+actionBody+"\"\r\n");
			this.actionBody = actionBody;
		}
	}
	
	/**
	 * 设置操作的IP数值
	 */
	public void setActionIp(String actionIp)
	{
		if ((!String.valueOf(this.actionIp).equals(String.valueOf(actionIp)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("action_ip")){ 
				this.LIST_COL_UPDATED.add("action_ip");
			}
			this._CHANGED_INFO.append("字段action_ip由\""+this.actionIp+"\"修改为\""+actionIp+"\"\r\n");
			this.actionIp = actionIp;
		}
	}
	
	/**
	 * 设置操作的日期数值
	 */
	public void setActionDate(java.util.Date actionDate)
	{
		if ((this.actionDate!=null&&actionDate!=null&&!this.actionDate.equals(actionDate))||(this.actionDate!=actionDate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("action_date")){ 
				this.LIST_COL_UPDATED.add("action_date");
			}
			this._CHANGED_INFO.append("字段action_date由\""+this.actionDate+"\"修改为\""+actionDate+"\"\r\n");
			this.actionDate = actionDate;
		}
	}
	
	

	/**
	 * 构造器
	 */
	public SysActionLog(long id,long userId,int actionType,String actionModule,String actionCommand,String actionBody,String actionIp,java.util.Date actionDate){
	
		this.id = id;
		this.userId = userId;
		this.actionType = actionType;
		this.actionModule = actionModule;
		this.actionCommand = actionCommand;
		this.actionBody = actionBody;
		this.actionIp = actionIp;
		this.actionDate = actionDate;
		
	}
	
	/**
	 * 构造器
	 */
	public SysActionLog(){
	}
	

	
	/**
	 * 重载toString方法
	 */
	public String toString(){
		StringBuilder sb = new StringBuilder(_SEPARATE_LINE+"表SysActionLog，主键\""+this.id+"\"的全部信息为:\r\n");
		sb.append("字段id数值为:"+id+"\r\n");
		sb.append("字段user_id数值为:"+userId+"\r\n");
		sb.append("字段action_type数值为:"+actionType+"\r\n");
		sb.append("字段action_module数值为:"+actionModule+"\r\n");
		sb.append("字段action_command数值为:"+actionCommand+"\r\n");
		sb.append("字段action_body数值为:"+actionBody+"\r\n");
		sb.append("字段action_ip数值为:"+actionIp+"\r\n");
		sb.append("字段action_date数值为:"+actionDate+"\r\n");
		
		sb.append(_SEPARATE_LINE);
		return sb.toString();
	}

	/**
	* 克隆自身
	* @return<a name=""></a>
	*/
	public Object clone(){
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {}
		return o;
	}

	
}