
 //Generated By XCodeFactory
package org.guihuotv.search.web.pojo;

import uw.dm.util.*;
import java.util.*;
import java.io.Serializable;

/**
 * Title: Base table SysSequence的pojo类
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为ValueObject类，通过数据库表映像。
 */
public class SysSequence implements Serializable,Cloneable {

	private static final long serialVersionUID = 1L;
	
	/*
	 * 字段，类型map表
	 */
	public static final HashMap<String, Integer> MAP_COL_TYPE = new HashMap<String, Integer>();
	
	/*
	 * 原始名称，属性名称map表
	 */
	public static final HashMap<String, String> MAP_COL_NAME = new HashMap<String, String>();
	
	 
	static{
		
		MAP_COL_TYPE.put("table_name",DmObjectType.STRING);
		MAP_COL_NAME.put("table_name","tableName");
		
		MAP_COL_TYPE.put("sequence_id",DmObjectType.LONG);
		MAP_COL_NAME.put("sequence_id","sequenceId");
		
		MAP_COL_TYPE.put("table_desc",DmObjectType.STRING);
		MAP_COL_NAME.put("table_desc","tableDesc");
		
		MAP_COL_TYPE.put("increment_num",DmObjectType.INT);
		MAP_COL_NAME.put("increment_num","incrementNum");
		
		MAP_COL_TYPE.put("create_date",DmObjectType.DATE);
		MAP_COL_NAME.put("create_date","createDate");
		
		MAP_COL_TYPE.put("last_update",DmObjectType.DATE);
		MAP_COL_NAME.put("last_update","lastUpdate");
		
	}

	public static final String TABLE_NAME = "sys_sequence";
	
	
	public static final String COL_TABLE_NAME = "table_name";
	
	public static final String COL_SEQUENCE_ID = "sequence_id";
	
	public static final String COL_TABLE_DESC = "table_desc";
	
	public static final String COL_INCREMENT_NUM = "increment_num";
	
	public static final String COL_CREATE_DATE = "create_date";
	
	public static final String COL_LAST_UPDATE = "last_update";
	

	/*
	 * 轻量级状态下更新列表list
	 */
	public List<String> LIST_COL_UPDATED = null;
	
	/*
	 * 自定义的附属信息
	 */
	public Map<Object,Object> MAP_EXT_PROPERTY = null;
	
	/*
	 * 变更信息
	 */
	private StringBuilder _CHANGED_INFO = null;
	
	/*
	 * 分割行
	 */
	private static final String _SEPARATE_LINE = "************************************\r\n";
	

	/*
	 * 实际的表名
	 */
	public String CURRENT_TABLE_NAME = null;
	
	
	//属性定义区域
	
	
	/**
	 * 
	 */
	private String tableName = "";
	
	
	/**
	 * 
	 */
	private long sequenceId = 0l;
	
	
	/**
	 * 
	 */
	private String tableDesc = "";
	
	
	/**
	 * 
	 */
	private int incrementNum = 0;
	
	
	/**
	 * 
	 */
	private java.util.Date createDate = null;
	
	
	/**
	 * 
	 */
	private java.util.Date lastUpdate = null;
	
	
	/**
	 * 设置附加属性
	 */
	public void SET_EXT_PROPERTY(Object key,Object value){
		if (MAP_EXT_PROPERTY==null)
			MAP_EXT_PROPERTY = new LinkedHashMap<Object,Object>();
		MAP_EXT_PROPERTY.put(key,value);
	}
	
	/**
	 * 获得附加属性
	 */
	public Object GET_EXT_PROPERTY(Object key){
		if (MAP_EXT_PROPERTY!=null)
			return MAP_EXT_PROPERTY.get(key);
		else
			return null;
	}
	
	/**
	 * 获得附加属性MAP
	 */
	public Map<Object,Object> GET_EXT_PROPERTY_MAP(){
		return MAP_EXT_PROPERTY;
	}
	
	/**
	 * 获得更改的字段列表.
	 */
	public List<String> GET_UPDATED_COL_LIST(){
		return LIST_COL_UPDATED;
	}
	
	/**
	 * 得到_CHANGED_INFO
	 */
	public String GET_CHANGED_INFO(){
		if (this._CHANGED_INFO==null){
			return null;
		}else{
			this._CHANGED_INFO.append(_SEPARATE_LINE);
			return this._CHANGED_INFO.toString(); 
		}
	}
	
	
	/**
	 * 获取数值
	 */
	public String getTableName()
	{
		return this.tableName;
	}
	
	/**
	 * 获取数值
	 */
	public long getSequenceId()
	{
		return this.sequenceId;
	}
	
	/**
	 * 获取数值
	 */
	public String getTableDesc()
	{
		return this.tableDesc;
	}
	
	/**
	 * 获取数值
	 */
	public int getIncrementNum()
	{
		return this.incrementNum;
	}
	
	/**
	 * 获取数值
	 */
	public java.util.Date getCreateDate()
	{
		return this.createDate;
	}
	
	/**
	 * 获取数值
	 */
	public java.util.Date getLastUpdate()
	{
		return this.lastUpdate;
	}
	

	
	/**
	 * 初始化set相关的信息
	 */
	private void initSetInfo(){
			this.LIST_COL_UPDATED = new ArrayList<String>();
			this._CHANGED_INFO = new StringBuilder(_SEPARATE_LINE+"表SysSequence，主键\""+this.tableName+"\"变更信息为:\r\n");
	}

	
	/**
	 * 设置数值
	 */
	public void setTableName(String tableName)
	{
		if ((!String.valueOf(this.tableName).equals(String.valueOf(tableName)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("table_name")){ 
				this.LIST_COL_UPDATED.add("table_name");
			}
			this._CHANGED_INFO.append("字段table_name由\""+this.tableName+"\"修改为\""+tableName+"\"\r\n");
			this.tableName = tableName;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setSequenceId(long sequenceId)
	{
		if (this.sequenceId!=sequenceId){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("sequence_id")){ 
				this.LIST_COL_UPDATED.add("sequence_id");
			}
			this._CHANGED_INFO.append("字段sequence_id由\""+this.sequenceId+"\"修改为\""+sequenceId+"\"\r\n");
			this.sequenceId = sequenceId;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setTableDesc(String tableDesc)
	{
		if ((!String.valueOf(this.tableDesc).equals(String.valueOf(tableDesc)))){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("table_desc")){ 
				this.LIST_COL_UPDATED.add("table_desc");
			}
			this._CHANGED_INFO.append("字段table_desc由\""+this.tableDesc+"\"修改为\""+tableDesc+"\"\r\n");
			this.tableDesc = tableDesc;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setIncrementNum(int incrementNum)
	{
		if (this.incrementNum!=incrementNum){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("increment_num")){ 
				this.LIST_COL_UPDATED.add("increment_num");
			}
			this._CHANGED_INFO.append("字段increment_num由\""+this.incrementNum+"\"修改为\""+incrementNum+"\"\r\n");
			this.incrementNum = incrementNum;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setCreateDate(java.util.Date createDate)
	{
		if ((this.createDate!=null&&createDate!=null&&!this.createDate.equals(createDate))||(this.createDate!=createDate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("create_date")){ 
				this.LIST_COL_UPDATED.add("create_date");
			}
			this._CHANGED_INFO.append("字段create_date由\""+this.createDate+"\"修改为\""+createDate+"\"\r\n");
			this.createDate = createDate;
		}
	}
	
	/**
	 * 设置数值
	 */
	public void setLastUpdate(java.util.Date lastUpdate)
	{
		if ((this.lastUpdate!=null&&lastUpdate!=null&&!this.lastUpdate.equals(lastUpdate))||(this.lastUpdate!=lastUpdate)){
			if (this.LIST_COL_UPDATED==null){ 
				initSetInfo();
			}
			if (!this.LIST_COL_UPDATED.contains("last_update")){ 
				this.LIST_COL_UPDATED.add("last_update");
			}
			this._CHANGED_INFO.append("字段last_update由\""+this.lastUpdate+"\"修改为\""+lastUpdate+"\"\r\n");
			this.lastUpdate = lastUpdate;
		}
	}
	
	

	/**
	 * 构造器
	 */
	public SysSequence(String tableName,long sequenceId,String tableDesc,int incrementNum,java.util.Date createDate,java.util.Date lastUpdate){
	
		this.tableName = tableName;
		this.sequenceId = sequenceId;
		this.tableDesc = tableDesc;
		this.incrementNum = incrementNum;
		this.createDate = createDate;
		this.lastUpdate = lastUpdate;
		
	}
	
	/**
	 * 构造器
	 */
	public SysSequence(){
	}
	

	
	/**
	 * 重载toString方法
	 */
	public String toString(){
		StringBuilder sb = new StringBuilder(_SEPARATE_LINE+"表SysSequence，主键\""+this.tableName+"\"的全部信息为:\r\n");
		sb.append("字段table_name数值为:"+tableName+"\r\n");
		sb.append("字段sequence_id数值为:"+sequenceId+"\r\n");
		sb.append("字段table_desc数值为:"+tableDesc+"\r\n");
		sb.append("字段increment_num数值为:"+incrementNum+"\r\n");
		sb.append("字段create_date数值为:"+createDate+"\r\n");
		sb.append("字段last_update数值为:"+lastUpdate+"\r\n");
		
		sb.append(_SEPARATE_LINE);
		return sb.toString();
	}

	/**
	* 克隆自身
	* @return<a name=""></a>
	*/
	public Object clone(){
		Object o = null;
		try {
			o = super.clone();
		} catch (CloneNotSupportedException e) {}
		return o;
	}

	
}