
//Generated By XCodeFactory
package org.guihuotv.search.web.dao;

import uw.dm.*;
import uw.dm.impl.*;
import uw.dm.util.*;
import org.guihuotv.search.web.pojo.*;

import java.util.*;
import java.sql.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



/**
 * Title: Base table NgnMsg 的DAO类。
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为DAO类，通过数据库表映像，实现数据库的三个方法。
 */
public class NgnMsgDAO {

	private static final Logger logger = LoggerFactory.getLogger(NgnMsgDAO.class);

	/**
	 * 获得对象。
	 *
	 */
	public static NgnMsg load(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException
	{
		NgnMsg ngnMsg = null;
		if (colList==null){
			ngnMsg = selectFromDb(dao,tableName,whereSql,paramList);
		}else{
			ngnMsg = liteSelectFromDb(dao,tableName,colList,whereSql,paramList);
		}
		return ngnMsg;
	}


	
	/**
	 * 更新数据库。
	 * @throws UnauthorizedException
	 */
	public static void update(DAOFactoryImpl dao,String tableName,NgnMsg ngnMsg)  throws TransactionException
	{	
		if (ngnMsg.LIST_COL_UPDATED==null){//如果updatelist=null，说明肯定是完整模式
			updateToDb(dao,tableName,ngnMsg);
		}else{
			liteUpdateToDb(dao,tableName,ngnMsg);
		}
	}
	


	/**
	 * 建立对象。
	 *
	 */
	public static NgnMsg save(DAOFactoryImpl dao,String tableName,NgnMsg ngnMsg)  throws TransactionException
	{
		return insertIntoDb(dao,tableName,ngnMsg);
	}

	
	
	/**
	 * 向数据库中插入一条数据。
	 */
	private static NgnMsg insertIntoDb(DAOFactoryImpl dao,String tableName,NgnMsg ngnMsg)  throws TransactionException{
		String insertSql=
			"INSERT INTO "+(tableName==null?"ngn_msg":tableName) +
			"(id,userId,toUserId,msg,sendDate,status) "+
			"VALUES "+
			"(?,?,?,?,?,?) ";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_msg":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,insertSql);
			
			if (ngnMsg.getId()<=0) ngnMsg.setId(SequenceManager.nextId("ngn_msg"));
			
			pstmt.setLong(1,ngnMsg.getId());
			pstmt.setLong(2,ngnMsg.getUserid());
			pstmt.setLong(3,ngnMsg.getTouserid());
			pstmt.setString(4,ngnMsg.getMsg());
			pstmt.setTimestamp(5,DmValueUtils.dateToTimestamp(ngnMsg.getSenddate()));
			pstmt.setInt(6,ngnMsg.getStatus());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			 ngnMsg.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
		}
		catch( SQLException sqle ){
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnMsg.java:insertIntoDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnMsg;
	}

	/**
	 * 保存该对象数据到数据库中.
	 */
	private static  void updateToDb(DAOFactoryImpl dao,String tableName,NgnMsg ngnMsg)  throws TransactionException{
		String updateSql =
		"UPDATE "+(tableName==null?"ngn_msg":tableName)+" SET " +
		"userId=?,toUserId=?,msg=?,sendDate=?,status=? "+
		"WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_msg":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,updateSql);
			pstmt.setLong(1,ngnMsg.getUserid());
			pstmt.setLong(2,ngnMsg.getTouserid());
			pstmt.setString(3,ngnMsg.getMsg());
			pstmt.setTimestamp(4,DmValueUtils.dateToTimestamp(ngnMsg.getSenddate()));
			pstmt.setInt(5,ngnMsg.getStatus());
			
			pstmt.setLong(6,ngnMsg.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
			 ngnMsg.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnMsg.java:updateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	
	/**
	 * 轻量级保存该对象数据到数据库中.
	 */
	private static  void liteUpdateToDb(DAOFactoryImpl dao,String tableName,NgnMsg ngnMsg)  throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		List<String> list = ngnMsg.LIST_COL_UPDATED;
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE "+(tableName==null?"ngn_msg":tableName)+" set ");
        for (int i=0;i<list.size();i++){
        	if (i==0){
        		sb.append(list.get(i)+"=?");
        	}else{
				sb.append(","+list.get(i)+"=?");
			}
		}
		sb.append(" WHERE id=?");
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_msg":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,sb.toString());
			String col = "";
			for (int i=0;i<list.size();i++){
				col = list.get(i);
				DmReflectUtils.DAOLiteSaveReflect(pstmt,ngnMsg,i+1,NgnMsg.MAP_COL_NAME.get(col),NgnMsg.MAP_COL_TYPE.get(col));
			}
			
			col = "id";
			DmReflectUtils.DAOLiteSaveReflect(pstmt,ngnMsg,list.size()+1,NgnMsg.MAP_COL_NAME.get(col),NgnMsg.MAP_COL_TYPE.get(col));
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			ngnMsg.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnMsg.java:liteUpdateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	


	/**
	 * 从数据库装入该对象所需要的数据
	 */
	private static NgnMsg selectFromDb(DAOFactoryImpl dao,String tableName,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		NgnMsg ngnMsg= null;
		try {
			String loadSql =
			"SELECT id,userId,toUserId,msg,sendDate,status FROM "+(tableName==null?"ngn_msg":tableName)+" "+(whereSql==null?"WHERE id=?":whereSql);
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_msg":tableName),"read");
			pstmt = con.prepareStatement(loadSql);
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
			ngnMsg= new NgnMsg(rs.getLong("id"),rs.getLong("userId"),rs.getLong("toUserId"),DmValueUtils.nullToStr(rs.getString("msg")),rs.getTimestamp("sendDate"),rs.getInt("status"));
			ngnMsg.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnMsg.java:selectFromDb(): ", sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnMsg;
	}
	/**
	 * 轻量级载入对象.
	 */
	private static NgnMsg liteSelectFromDb(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		NgnMsg ngnMsg= null;
        StringBuilder sb = new StringBuilder();
        sb.append(" select ");
        for (int i=0;i<colList.length;i++){
        	if (i==0) {
        		sb.append(colList[i]);
        	}else{
				sb.append(","+colList[i]);
			}
		}
		sb.append(" FROM "+(tableName==null?"ngn_msg":tableName));
		sb.append(" ").append(whereSql==null?"WHERE id=?":whereSql);
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_msg":tableName),"read");
			pstmt = con.prepareStatement(sb.toString());
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
				ngnMsg = new NgnMsg();
				String col = "";
				for (int i=0;i<colList.length;i++){
					col = colList[i];
					DmReflectUtils.DAOLiteLoadReflect(rs,ngnMsg,col,NgnMsg.MAP_COL_NAME.get(col),NgnMsg.MAP_COL_TYPE.get(col));
				}
				ngnMsg.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnMsg.java:liteSelectFromDb(): " , sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnMsg;
	}

	
	/**
	 * 删除数据。
	 */
	public static void delete(DAOFactoryImpl dao,String tableName,NgnMsg ngnMsg)  throws TransactionException
	{
		deleteFromDb(dao,tableName,ngnMsg);
	}

	/**
	 * 直接从数据库中删除数据.
	 */
	private static void deleteFromDb(DAOFactoryImpl dao,String tableName,NgnMsg ngnMsg)  throws TransactionException
	{
		String deleteSql = 
		"DELETE FROM "+(tableName==null?"ngn_msg":tableName)+" WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_msg":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,deleteSql);
			pstmt.setLong(1,ngnMsg.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnMsg.java:deleteFromDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}

	

}