
//Generated By XCodeFactory
package org.guihuotv.search.web.dao;

import uw.dm.*;
import uw.dm.impl.*;
import uw.dm.util.*;
import org.guihuotv.search.web.pojo.*;

import java.util.*;
import java.sql.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



/**
 * Title: Base table NgnSearch 的DAO类。
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为DAO类，通过数据库表映像，实现数据库的三个方法。
 */
public class NgnSearchDAO {

	private static final Logger logger = LoggerFactory.getLogger(NgnSearchDAO.class);

	/**
	 * 获得对象。
	 *
	 */
	public static NgnSearch load(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException
	{
		NgnSearch ngnSearch = null;
		if (colList==null){
			ngnSearch = selectFromDb(dao,tableName,whereSql,paramList);
		}else{
			ngnSearch = liteSelectFromDb(dao,tableName,colList,whereSql,paramList);
		}
		return ngnSearch;
	}


	
	/**
	 * 更新数据库。
	 * @throws UnauthorizedException
	 */
	public static void update(DAOFactoryImpl dao,String tableName,NgnSearch ngnSearch)  throws TransactionException
	{	
		if (ngnSearch.LIST_COL_UPDATED==null){//如果updatelist=null，说明肯定是完整模式
			updateToDb(dao,tableName,ngnSearch);
		}else{
			liteUpdateToDb(dao,tableName,ngnSearch);
		}
	}
	


	/**
	 * 建立对象。
	 *
	 */
	public static NgnSearch save(DAOFactoryImpl dao,String tableName,NgnSearch ngnSearch)  throws TransactionException
	{
		return insertIntoDb(dao,tableName,ngnSearch);
	}

	
	
	/**
	 * 向数据库中插入一条数据。
	 */
	private static NgnSearch insertIntoDb(DAOFactoryImpl dao,String tableName,NgnSearch ngnSearch)  throws TransactionException{
		String insertSql=
			"INSERT INTO "+(tableName==null?"ngn_search":tableName) +
			"(id,user_id,searchUrl,status) "+
			"VALUES "+
			"(?,?,?,?) ";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_search":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,insertSql);
			
			if (ngnSearch.getId()<=0) ngnSearch.setId(SequenceManager.nextId("ngn_search"));
			
			pstmt.setLong(1,ngnSearch.getId());
			pstmt.setLong(2,ngnSearch.getUserId());
			pstmt.setString(3,ngnSearch.getSearchurl());
			pstmt.setInt(4,ngnSearch.getStatus());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			 ngnSearch.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
		}
		catch( SQLException sqle ){
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSearch.java:insertIntoDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnSearch;
	}

	/**
	 * 保存该对象数据到数据库中.
	 */
	private static  void updateToDb(DAOFactoryImpl dao,String tableName,NgnSearch ngnSearch)  throws TransactionException{
		String updateSql =
		"UPDATE "+(tableName==null?"ngn_search":tableName)+" SET " +
		"user_id=?,searchUrl=?,status=? "+
		"WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_search":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,updateSql);
			pstmt.setLong(1,ngnSearch.getUserId());
			pstmt.setString(2,ngnSearch.getSearchurl());
			pstmt.setInt(3,ngnSearch.getStatus());
			
			pstmt.setLong(4,ngnSearch.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
			 ngnSearch.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSearch.java:updateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	
	/**
	 * 轻量级保存该对象数据到数据库中.
	 */
	private static  void liteUpdateToDb(DAOFactoryImpl dao,String tableName,NgnSearch ngnSearch)  throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		List<String> list = ngnSearch.LIST_COL_UPDATED;
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE "+(tableName==null?"ngn_search":tableName)+" set ");
        for (int i=0;i<list.size();i++){
        	if (i==0){
        		sb.append(list.get(i)+"=?");
        	}else{
				sb.append(","+list.get(i)+"=?");
			}
		}
		sb.append(" WHERE id=?");
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_search":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,sb.toString());
			String col = "";
			for (int i=0;i<list.size();i++){
				col = list.get(i);
				DmReflectUtils.DAOLiteSaveReflect(pstmt,ngnSearch,i+1,NgnSearch.MAP_COL_NAME.get(col),NgnSearch.MAP_COL_TYPE.get(col));
			}
			
			col = "id";
			DmReflectUtils.DAOLiteSaveReflect(pstmt,ngnSearch,list.size()+1,NgnSearch.MAP_COL_NAME.get(col),NgnSearch.MAP_COL_TYPE.get(col));
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			ngnSearch.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSearch.java:liteUpdateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	


	/**
	 * 从数据库装入该对象所需要的数据
	 */
	private static NgnSearch selectFromDb(DAOFactoryImpl dao,String tableName,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		NgnSearch ngnSearch= null;
		try {
			String loadSql =
			"SELECT id,user_id,searchUrl,status FROM "+(tableName==null?"ngn_search":tableName)+" "+(whereSql==null?"WHERE id=?":whereSql);
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_search":tableName),"read");
			pstmt = con.prepareStatement(loadSql);
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
			ngnSearch= new NgnSearch(rs.getLong("id"),rs.getLong("user_id"),DmValueUtils.nullToStr(rs.getString("searchUrl")),rs.getInt("status"));
			ngnSearch.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSearch.java:selectFromDb(): ", sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnSearch;
	}
	/**
	 * 轻量级载入对象.
	 */
	private static NgnSearch liteSelectFromDb(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		NgnSearch ngnSearch= null;
        StringBuilder sb = new StringBuilder();
        sb.append(" select ");
        for (int i=0;i<colList.length;i++){
        	if (i==0) {
        		sb.append(colList[i]);
        	}else{
				sb.append(","+colList[i]);
			}
		}
		sb.append(" FROM "+(tableName==null?"ngn_search":tableName));
		sb.append(" ").append(whereSql==null?"WHERE id=?":whereSql);
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_search":tableName),"read");
			pstmt = con.prepareStatement(sb.toString());
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
				ngnSearch = new NgnSearch();
				String col = "";
				for (int i=0;i<colList.length;i++){
					col = colList[i];
					DmReflectUtils.DAOLiteLoadReflect(rs,ngnSearch,col,NgnSearch.MAP_COL_NAME.get(col),NgnSearch.MAP_COL_TYPE.get(col));
				}
				ngnSearch.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSearch.java:liteSelectFromDb(): " , sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnSearch;
	}

	
	/**
	 * 删除数据。
	 */
	public static void delete(DAOFactoryImpl dao,String tableName,NgnSearch ngnSearch)  throws TransactionException
	{
		deleteFromDb(dao,tableName,ngnSearch);
	}

	/**
	 * 直接从数据库中删除数据.
	 */
	private static void deleteFromDb(DAOFactoryImpl dao,String tableName,NgnSearch ngnSearch)  throws TransactionException
	{
		String deleteSql = 
		"DELETE FROM "+(tableName==null?"ngn_search":tableName)+" WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_search":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,deleteSql);
			pstmt.setLong(1,ngnSearch.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSearch.java:deleteFromDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}

	

}