
//Generated By XCodeFactory
package org.guihuotv.search.web.dao;

import uw.dm.*;
import uw.dm.impl.*;
import uw.dm.util.*;
import org.guihuotv.search.web.pojo.*;

import java.util.*;
import java.sql.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



/**
 * Title: Base table NgnSay 的DAO类。
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为DAO类，通过数据库表映像，实现数据库的三个方法。
 */
public class NgnSayDAO {

	private static final Logger logger = LoggerFactory.getLogger(NgnSayDAO.class);

	/**
	 * 获得对象。
	 *
	 */
	public static NgnSay load(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException
	{
		NgnSay ngnSay = null;
		if (colList==null){
			ngnSay = selectFromDb(dao,tableName,whereSql,paramList);
		}else{
			ngnSay = liteSelectFromDb(dao,tableName,colList,whereSql,paramList);
		}
		return ngnSay;
	}


	
	/**
	 * 更新数据库。
	 * @throws UnauthorizedException
	 */
	public static void update(DAOFactoryImpl dao,String tableName,NgnSay ngnSay)  throws TransactionException
	{	
		if (ngnSay.LIST_COL_UPDATED==null){//如果updatelist=null，说明肯定是完整模式
			updateToDb(dao,tableName,ngnSay);
		}else{
			liteUpdateToDb(dao,tableName,ngnSay);
		}
	}
	


	/**
	 * 建立对象。
	 *
	 */
	public static NgnSay save(DAOFactoryImpl dao,String tableName,NgnSay ngnSay)  throws TransactionException
	{
		return insertIntoDb(dao,tableName,ngnSay);
	}

	
	
	/**
	 * 向数据库中插入一条数据。
	 */
	private static NgnSay insertIntoDb(DAOFactoryImpl dao,String tableName,NgnSay ngnSay)  throws TransactionException{
		String insertSql=
			"INSERT INTO "+(tableName==null?"ngn_say":tableName) +
			"(id,userSay,sysCmd,cmdContent,cmdP1,cmdP2,cmdP3,cmdP4,cmdP5,createTime,status) "+
			"VALUES "+
			"(?,?,?,?,?,?,?,?,?,?,?) ";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_say":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,insertSql);
			
			if (ngnSay.getId()<=0) ngnSay.setId(SequenceManager.nextId("ngn_say"));
			
			pstmt.setLong(1,ngnSay.getId());
			pstmt.setString(2,ngnSay.getUsersay());
			pstmt.setString(3,ngnSay.getSyscmd());
			pstmt.setString(4,ngnSay.getCmdcontent());
			pstmt.setString(5,ngnSay.getCmdp1());
			pstmt.setString(6,ngnSay.getCmdp2());
			pstmt.setString(7,ngnSay.getCmdp3());
			pstmt.setString(8,ngnSay.getCmdp4());
			pstmt.setString(9,ngnSay.getCmdp5());
			pstmt.setTimestamp(10,DmValueUtils.dateToTimestamp(ngnSay.getCreatetime()));
			pstmt.setInt(11,ngnSay.getStatus());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			 ngnSay.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
		}
		catch( SQLException sqle ){
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSay.java:insertIntoDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnSay;
	}

	/**
	 * 保存该对象数据到数据库中.
	 */
	private static  void updateToDb(DAOFactoryImpl dao,String tableName,NgnSay ngnSay)  throws TransactionException{
		String updateSql =
		"UPDATE "+(tableName==null?"ngn_say":tableName)+" SET " +
		"userSay=?,sysCmd=?,cmdContent=?,cmdP1=?,cmdP2=?,cmdP3=?,cmdP4=?,cmdP5=?,createTime=?,status=? "+
		"WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_say":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,updateSql);
			pstmt.setString(1,ngnSay.getUsersay());
			pstmt.setString(2,ngnSay.getSyscmd());
			pstmt.setString(3,ngnSay.getCmdcontent());
			pstmt.setString(4,ngnSay.getCmdp1());
			pstmt.setString(5,ngnSay.getCmdp2());
			pstmt.setString(6,ngnSay.getCmdp3());
			pstmt.setString(7,ngnSay.getCmdp4());
			pstmt.setString(8,ngnSay.getCmdp5());
			pstmt.setTimestamp(9,DmValueUtils.dateToTimestamp(ngnSay.getCreatetime()));
			pstmt.setInt(10,ngnSay.getStatus());
			
			pstmt.setLong(11,ngnSay.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
			 ngnSay.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSay.java:updateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	
	/**
	 * 轻量级保存该对象数据到数据库中.
	 */
	private static  void liteUpdateToDb(DAOFactoryImpl dao,String tableName,NgnSay ngnSay)  throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		List<String> list = ngnSay.LIST_COL_UPDATED;
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE "+(tableName==null?"ngn_say":tableName)+" set ");
        for (int i=0;i<list.size();i++){
        	if (i==0){
        		sb.append(list.get(i)+"=?");
        	}else{
				sb.append(","+list.get(i)+"=?");
			}
		}
		sb.append(" WHERE id=?");
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_say":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,sb.toString());
			String col = "";
			for (int i=0;i<list.size();i++){
				col = list.get(i);
				DmReflectUtils.DAOLiteSaveReflect(pstmt,ngnSay,i+1,NgnSay.MAP_COL_NAME.get(col),NgnSay.MAP_COL_TYPE.get(col));
			}
			
			col = "id";
			DmReflectUtils.DAOLiteSaveReflect(pstmt,ngnSay,list.size()+1,NgnSay.MAP_COL_NAME.get(col),NgnSay.MAP_COL_TYPE.get(col));
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			ngnSay.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSay.java:liteUpdateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	


	/**
	 * 从数据库装入该对象所需要的数据
	 */
	private static NgnSay selectFromDb(DAOFactoryImpl dao,String tableName,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		NgnSay ngnSay= null;
		try {
			String loadSql =
			"SELECT id,userSay,sysCmd,cmdContent,cmdP1,cmdP2,cmdP3,cmdP4,cmdP5,createTime,status FROM "+(tableName==null?"ngn_say":tableName)+" "+(whereSql==null?"WHERE id=?":whereSql);
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_say":tableName),"read");
			pstmt = con.prepareStatement(loadSql);
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
			ngnSay= new NgnSay(rs.getLong("id"),DmValueUtils.nullToStr(rs.getString("userSay")),DmValueUtils.nullToStr(rs.getString("sysCmd")),DmValueUtils.nullToStr(rs.getString("cmdContent")),DmValueUtils.nullToStr(rs.getString("cmdP1")),DmValueUtils.nullToStr(rs.getString("cmdP2")),DmValueUtils.nullToStr(rs.getString("cmdP3")),DmValueUtils.nullToStr(rs.getString("cmdP4")),DmValueUtils.nullToStr(rs.getString("cmdP5")),rs.getTimestamp("createTime"),rs.getInt("status"));
			ngnSay.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSay.java:selectFromDb(): ", sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnSay;
	}
	/**
	 * 轻量级载入对象.
	 */
	private static NgnSay liteSelectFromDb(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		NgnSay ngnSay= null;
        StringBuilder sb = new StringBuilder();
        sb.append(" select ");
        for (int i=0;i<colList.length;i++){
        	if (i==0) {
        		sb.append(colList[i]);
        	}else{
				sb.append(","+colList[i]);
			}
		}
		sb.append(" FROM "+(tableName==null?"ngn_say":tableName));
		sb.append(" ").append(whereSql==null?"WHERE id=?":whereSql);
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_say":tableName),"read");
			pstmt = con.prepareStatement(sb.toString());
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
				ngnSay = new NgnSay();
				String col = "";
				for (int i=0;i<colList.length;i++){
					col = colList[i];
					DmReflectUtils.DAOLiteLoadReflect(rs,ngnSay,col,NgnSay.MAP_COL_NAME.get(col),NgnSay.MAP_COL_TYPE.get(col));
				}
				ngnSay.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSay.java:liteSelectFromDb(): " , sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnSay;
	}

	
	/**
	 * 删除数据。
	 */
	public static void delete(DAOFactoryImpl dao,String tableName,NgnSay ngnSay)  throws TransactionException
	{
		deleteFromDb(dao,tableName,ngnSay);
	}

	/**
	 * 直接从数据库中删除数据.
	 */
	private static void deleteFromDb(DAOFactoryImpl dao,String tableName,NgnSay ngnSay)  throws TransactionException
	{
		String deleteSql = 
		"DELETE FROM "+(tableName==null?"ngn_say":tableName)+" WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_say":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,deleteSql);
			pstmt.setLong(1,ngnSay.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnSay.java:deleteFromDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}

	

}