
//Generated By XCodeFactory
package org.guihuotv.search.web.dao;

import uw.dm.*;
import uw.dm.impl.*;
import uw.dm.util.*;
import org.guihuotv.search.web.pojo.*;

import java.util.*;
import java.sql.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



/**
 * Title: Base table NgnTimer 的DAO类。
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为DAO类，通过数据库表映像，实现数据库的三个方法。
 */
public class NgnTimerDAO {

	private static final Logger logger = LoggerFactory.getLogger(NgnTimerDAO.class);

	/**
	 * 获得对象。
	 *
	 */
	public static NgnTimer load(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException
	{
		NgnTimer ngnTimer = null;
		if (colList==null){
			ngnTimer = selectFromDb(dao,tableName,whereSql,paramList);
		}else{
			ngnTimer = liteSelectFromDb(dao,tableName,colList,whereSql,paramList);
		}
		return ngnTimer;
	}


	
	/**
	 * 更新数据库。
	 * @throws UnauthorizedException
	 */
	public static void update(DAOFactoryImpl dao,String tableName,NgnTimer ngnTimer)  throws TransactionException
	{	
		if (ngnTimer.LIST_COL_UPDATED==null){//如果updatelist=null，说明肯定是完整模式
			updateToDb(dao,tableName,ngnTimer);
		}else{
			liteUpdateToDb(dao,tableName,ngnTimer);
		}
	}
	


	/**
	 * 建立对象。
	 *
	 */
	public static NgnTimer save(DAOFactoryImpl dao,String tableName,NgnTimer ngnTimer)  throws TransactionException
	{
		return insertIntoDb(dao,tableName,ngnTimer);
	}

	
	
	/**
	 * 向数据库中插入一条数据。
	 */
	private static NgnTimer insertIntoDb(DAOFactoryImpl dao,String tableName,NgnTimer ngnTimer)  throws TransactionException{
		String insertSql=
			"INSERT INTO "+(tableName==null?"ngn_timer":tableName) +
			"(id,name,timerType,timer,timerUrl,p1,p2,p3,createTime,status) "+
			"VALUES "+
			"(?,?,?,?,?,?,?,?,?,?) ";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_timer":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,insertSql);
			
			if (ngnTimer.getId()<=0) ngnTimer.setId(SequenceManager.nextId("ngn_timer"));
			
			pstmt.setLong(1,ngnTimer.getId());
			pstmt.setString(2,ngnTimer.getName());
			pstmt.setInt(3,ngnTimer.getTimertype());
			pstmt.setTimestamp(4,DmValueUtils.dateToTimestamp(ngnTimer.getTimer()));
			pstmt.setString(5,ngnTimer.getTimerurl());
			pstmt.setString(6,ngnTimer.getP1());
			pstmt.setString(7,ngnTimer.getP2());
			pstmt.setString(8,ngnTimer.getP3());
			pstmt.setTimestamp(9,DmValueUtils.dateToTimestamp(ngnTimer.getCreatetime()));
			pstmt.setInt(10,ngnTimer.getStatus());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			 ngnTimer.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
		}
		catch( SQLException sqle ){
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnTimer.java:insertIntoDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnTimer;
	}

	/**
	 * 保存该对象数据到数据库中.
	 */
	private static  void updateToDb(DAOFactoryImpl dao,String tableName,NgnTimer ngnTimer)  throws TransactionException{
		String updateSql =
		"UPDATE "+(tableName==null?"ngn_timer":tableName)+" SET " +
		"name=?,timerType=?,timer=?,timerUrl=?,p1=?,p2=?,p3=?,createTime=?,status=? "+
		"WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_timer":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,updateSql);
			pstmt.setString(1,ngnTimer.getName());
			pstmt.setInt(2,ngnTimer.getTimertype());
			pstmt.setTimestamp(3,DmValueUtils.dateToTimestamp(ngnTimer.getTimer()));
			pstmt.setString(4,ngnTimer.getTimerurl());
			pstmt.setString(5,ngnTimer.getP1());
			pstmt.setString(6,ngnTimer.getP2());
			pstmt.setString(7,ngnTimer.getP3());
			pstmt.setTimestamp(8,DmValueUtils.dateToTimestamp(ngnTimer.getCreatetime()));
			pstmt.setInt(9,ngnTimer.getStatus());
			
			pstmt.setLong(10,ngnTimer.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
			 ngnTimer.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnTimer.java:updateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	
	/**
	 * 轻量级保存该对象数据到数据库中.
	 */
	private static  void liteUpdateToDb(DAOFactoryImpl dao,String tableName,NgnTimer ngnTimer)  throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		List<String> list = ngnTimer.LIST_COL_UPDATED;
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE "+(tableName==null?"ngn_timer":tableName)+" set ");
        for (int i=0;i<list.size();i++){
        	if (i==0){
        		sb.append(list.get(i)+"=?");
        	}else{
				sb.append(","+list.get(i)+"=?");
			}
		}
		sb.append(" WHERE id=?");
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_timer":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,sb.toString());
			String col = "";
			for (int i=0;i<list.size();i++){
				col = list.get(i);
				DmReflectUtils.DAOLiteSaveReflect(pstmt,ngnTimer,i+1,NgnTimer.MAP_COL_NAME.get(col),NgnTimer.MAP_COL_TYPE.get(col));
			}
			
			col = "id";
			DmReflectUtils.DAOLiteSaveReflect(pstmt,ngnTimer,list.size()+1,NgnTimer.MAP_COL_NAME.get(col),NgnTimer.MAP_COL_TYPE.get(col));
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			ngnTimer.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnTimer.java:liteUpdateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	


	/**
	 * 从数据库装入该对象所需要的数据
	 */
	private static NgnTimer selectFromDb(DAOFactoryImpl dao,String tableName,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		NgnTimer ngnTimer= null;
		try {
			String loadSql =
			"SELECT id,name,timerType,timer,timerUrl,p1,p2,p3,createTime,status FROM "+(tableName==null?"ngn_timer":tableName)+" "+(whereSql==null?"WHERE id=?":whereSql);
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_timer":tableName),"read");
			pstmt = con.prepareStatement(loadSql);
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
			ngnTimer= new NgnTimer(rs.getLong("id"),DmValueUtils.nullToStr(rs.getString("name")),rs.getInt("timerType"),rs.getTimestamp("timer"),DmValueUtils.nullToStr(rs.getString("timerUrl")),DmValueUtils.nullToStr(rs.getString("p1")),DmValueUtils.nullToStr(rs.getString("p2")),DmValueUtils.nullToStr(rs.getString("p3")),rs.getTimestamp("createTime"),rs.getInt("status"));
			ngnTimer.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnTimer.java:selectFromDb(): ", sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnTimer;
	}
	/**
	 * 轻量级载入对象.
	 */
	private static NgnTimer liteSelectFromDb(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		NgnTimer ngnTimer= null;
        StringBuilder sb = new StringBuilder();
        sb.append(" select ");
        for (int i=0;i<colList.length;i++){
        	if (i==0) {
        		sb.append(colList[i]);
        	}else{
				sb.append(","+colList[i]);
			}
		}
		sb.append(" FROM "+(tableName==null?"ngn_timer":tableName));
		sb.append(" ").append(whereSql==null?"WHERE id=?":whereSql);
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_timer":tableName),"read");
			pstmt = con.prepareStatement(sb.toString());
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
				ngnTimer = new NgnTimer();
				String col = "";
				for (int i=0;i<colList.length;i++){
					col = colList[i];
					DmReflectUtils.DAOLiteLoadReflect(rs,ngnTimer,col,NgnTimer.MAP_COL_NAME.get(col),NgnTimer.MAP_COL_TYPE.get(col));
				}
				ngnTimer.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnTimer.java:liteSelectFromDb(): " , sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return ngnTimer;
	}

	
	/**
	 * 删除数据。
	 */
	public static void delete(DAOFactoryImpl dao,String tableName,NgnTimer ngnTimer)  throws TransactionException
	{
		deleteFromDb(dao,tableName,ngnTimer);
	}

	/**
	 * 直接从数据库中删除数据.
	 */
	private static void deleteFromDb(DAOFactoryImpl dao,String tableName,NgnTimer ngnTimer)  throws TransactionException
	{
		String deleteSql = 
		"DELETE FROM "+(tableName==null?"ngn_timer":tableName)+" WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"ngn_timer":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,deleteSql);
			pstmt.setLong(1,ngnTimer.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbNgnTimer.java:deleteFromDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}

	

}