
//Generated By XCodeFactory
package org.guihuotv.search.web.dao;

import uw.dm.*;
import uw.dm.impl.*;
import uw.dm.util.*;
import org.guihuotv.search.web.pojo.*;

import java.util.*;
import java.sql.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



/**
 * Title: Base table SysActionLog 的DAO类。
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为DAO类，通过数据库表映像，实现数据库的三个方法。
 */
public class SysActionLogDAO {

	private static final Logger logger = LoggerFactory.getLogger(SysActionLogDAO.class);

	/**
	 * 获得对象。
	 *
	 */
	public static SysActionLog load(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException
	{
		SysActionLog sysActionLog = null;
		if (colList==null){
			sysActionLog = selectFromDb(dao,tableName,whereSql,paramList);
		}else{
			sysActionLog = liteSelectFromDb(dao,tableName,colList,whereSql,paramList);
		}
		return sysActionLog;
	}


	
	/**
	 * 更新数据库。
	 * @throws UnauthorizedException
	 */
	public static void update(DAOFactoryImpl dao,String tableName,SysActionLog sysActionLog)  throws TransactionException
	{	
		if (sysActionLog.LIST_COL_UPDATED==null){//如果updatelist=null，说明肯定是完整模式
			updateToDb(dao,tableName,sysActionLog);
		}else{
			liteUpdateToDb(dao,tableName,sysActionLog);
		}
	}
	


	/**
	 * 建立对象。
	 *
	 */
	public static SysActionLog save(DAOFactoryImpl dao,String tableName,SysActionLog sysActionLog)  throws TransactionException
	{
		return insertIntoDb(dao,tableName,sysActionLog);
	}

	
	
	/**
	 * 向数据库中插入一条数据。
	 */
	private static SysActionLog insertIntoDb(DAOFactoryImpl dao,String tableName,SysActionLog sysActionLog)  throws TransactionException{
		String insertSql=
			"INSERT INTO "+(tableName==null?"sys_action_log":tableName) +
			"(id,user_id,action_type,action_module,action_command,action_body,action_ip,action_date) "+
			"VALUES "+
			"(?,?,?,?,?,?,?,?) ";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_action_log":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,insertSql);
			
			if (sysActionLog.getId()<=0) sysActionLog.setId(SequenceManager.nextId("sys_action_log"));
			
			pstmt.setLong(1,sysActionLog.getId());
			pstmt.setLong(2,sysActionLog.getUserId());
			pstmt.setInt(3,sysActionLog.getActionType());
			pstmt.setString(4,sysActionLog.getActionModule());
			pstmt.setString(5,sysActionLog.getActionCommand());
			pstmt.setString(6,sysActionLog.getActionBody());
			pstmt.setString(7,sysActionLog.getActionIp());
			pstmt.setTimestamp(8,DmValueUtils.dateToTimestamp(sysActionLog.getActionDate()));
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			 sysActionLog.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
		}
		catch( SQLException sqle ){
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysActionLog.java:insertIntoDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return sysActionLog;
	}

	/**
	 * 保存该对象数据到数据库中.
	 */
	private static  void updateToDb(DAOFactoryImpl dao,String tableName,SysActionLog sysActionLog)  throws TransactionException{
		String updateSql =
		"UPDATE "+(tableName==null?"sys_action_log":tableName)+" SET " +
		"user_id=?,action_type=?,action_module=?,action_command=?,action_body=?,action_ip=?,action_date=? "+
		"WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_action_log":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,updateSql);
			pstmt.setLong(1,sysActionLog.getUserId());
			pstmt.setInt(2,sysActionLog.getActionType());
			pstmt.setString(3,sysActionLog.getActionModule());
			pstmt.setString(4,sysActionLog.getActionCommand());
			pstmt.setString(5,sysActionLog.getActionBody());
			pstmt.setString(6,sysActionLog.getActionIp());
			pstmt.setTimestamp(7,DmValueUtils.dateToTimestamp(sysActionLog.getActionDate()));
			
			pstmt.setLong(8,sysActionLog.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
			 sysActionLog.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysActionLog.java:updateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	
	/**
	 * 轻量级保存该对象数据到数据库中.
	 */
	private static  void liteUpdateToDb(DAOFactoryImpl dao,String tableName,SysActionLog sysActionLog)  throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		List<String> list = sysActionLog.LIST_COL_UPDATED;
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE "+(tableName==null?"sys_action_log":tableName)+" set ");
        for (int i=0;i<list.size();i++){
        	if (i==0){
        		sb.append(list.get(i)+"=?");
        	}else{
				sb.append(","+list.get(i)+"=?");
			}
		}
		sb.append(" WHERE id=?");
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_action_log":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,sb.toString());
			String col = "";
			for (int i=0;i<list.size();i++){
				col = list.get(i);
				DmReflectUtils.DAOLiteSaveReflect(pstmt,sysActionLog,i+1,SysActionLog.MAP_COL_NAME.get(col),SysActionLog.MAP_COL_TYPE.get(col));
			}
			
			col = "id";
			DmReflectUtils.DAOLiteSaveReflect(pstmt,sysActionLog,list.size()+1,SysActionLog.MAP_COL_NAME.get(col),SysActionLog.MAP_COL_TYPE.get(col));
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			sysActionLog.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysActionLog.java:liteUpdateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	


	/**
	 * 从数据库装入该对象所需要的数据
	 */
	private static SysActionLog selectFromDb(DAOFactoryImpl dao,String tableName,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		SysActionLog sysActionLog= null;
		try {
			String loadSql =
			"SELECT id,user_id,action_type,action_module,action_command,action_body,action_ip,action_date FROM "+(tableName==null?"sys_action_log":tableName)+" "+(whereSql==null?"WHERE id=?":whereSql);
			con = dao.getTransactionController().getConnection((tableName==null?"sys_action_log":tableName),"read");
			pstmt = con.prepareStatement(loadSql);
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
			sysActionLog= new SysActionLog(rs.getLong("id"),rs.getLong("user_id"),rs.getInt("action_type"),DmValueUtils.nullToStr(rs.getString("action_module")),DmValueUtils.nullToStr(rs.getString("action_command")),DmValueUtils.nullToStr(rs.getString("action_body")),DmValueUtils.nullToStr(rs.getString("action_ip")),rs.getTimestamp("action_date"));
			sysActionLog.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysActionLog.java:selectFromDb(): ", sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return sysActionLog;
	}
	/**
	 * 轻量级载入对象.
	 */
	private static SysActionLog liteSelectFromDb(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		SysActionLog sysActionLog= null;
        StringBuilder sb = new StringBuilder();
        sb.append(" select ");
        for (int i=0;i<colList.length;i++){
        	if (i==0) {
        		sb.append(colList[i]);
        	}else{
				sb.append(","+colList[i]);
			}
		}
		sb.append(" FROM "+(tableName==null?"sys_action_log":tableName));
		sb.append(" ").append(whereSql==null?"WHERE id=?":whereSql);
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_action_log":tableName),"read");
			pstmt = con.prepareStatement(sb.toString());
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
				sysActionLog = new SysActionLog();
				String col = "";
				for (int i=0;i<colList.length;i++){
					col = colList[i];
					DmReflectUtils.DAOLiteLoadReflect(rs,sysActionLog,col,SysActionLog.MAP_COL_NAME.get(col),SysActionLog.MAP_COL_TYPE.get(col));
				}
				sysActionLog.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysActionLog.java:liteSelectFromDb(): " , sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return sysActionLog;
	}

	
	/**
	 * 删除数据。
	 */
	public static void delete(DAOFactoryImpl dao,String tableName,SysActionLog sysActionLog)  throws TransactionException
	{
		deleteFromDb(dao,tableName,sysActionLog);
	}

	/**
	 * 直接从数据库中删除数据.
	 */
	private static void deleteFromDb(DAOFactoryImpl dao,String tableName,SysActionLog sysActionLog)  throws TransactionException
	{
		String deleteSql = 
		"DELETE FROM "+(tableName==null?"sys_action_log":tableName)+" WHERE id=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_action_log":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,deleteSql);
			pstmt.setLong(1,sysActionLog.getId());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysActionLog.java:deleteFromDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}

	

}