
//Generated By XCodeFactory
package org.guihuotv.search.web.dao;

import uw.dm.*;
import uw.dm.impl.*;
import uw.dm.util.*;
import org.guihuotv.search.web.pojo.*;

import java.util.*;
import java.sql.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;



/**
 * Title: Base table SysSequence 的DAO类。
 * Description: 本文件使用XCodeFactory自动生成。
 * 本类为DAO类，通过数据库表映像，实现数据库的三个方法。
 */
public class SysSequenceDAO {

	private static final Logger logger = LoggerFactory.getLogger(SysSequenceDAO.class);

	/**
	 * 获得对象。
	 *
	 */
	public static SysSequence load(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException
	{
		SysSequence sysSequence = null;
		if (colList==null){
			sysSequence = selectFromDb(dao,tableName,whereSql,paramList);
		}else{
			sysSequence = liteSelectFromDb(dao,tableName,colList,whereSql,paramList);
		}
		return sysSequence;
	}


	
	/**
	 * 更新数据库。
	 * @throws UnauthorizedException
	 */
	public static void update(DAOFactoryImpl dao,String tableName,SysSequence sysSequence)  throws TransactionException
	{	
		if (sysSequence.LIST_COL_UPDATED==null){//如果updatelist=null，说明肯定是完整模式
			updateToDb(dao,tableName,sysSequence);
		}else{
			liteUpdateToDb(dao,tableName,sysSequence);
		}
	}
	


	/**
	 * 建立对象。
	 *
	 */
	public static SysSequence save(DAOFactoryImpl dao,String tableName,SysSequence sysSequence)  throws TransactionException
	{
		return insertIntoDb(dao,tableName,sysSequence);
	}

	
	
	/**
	 * 向数据库中插入一条数据。
	 */
	private static SysSequence insertIntoDb(DAOFactoryImpl dao,String tableName,SysSequence sysSequence)  throws TransactionException{
		String insertSql=
			"INSERT INTO "+(tableName==null?"sys_sequence":tableName) +
			"(table_name,sequence_id,table_desc,increment_num,create_date,last_update) "+
			"VALUES "+
			"(?,?,?,?,?,?) ";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_sequence":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,insertSql);
			
			
			
			pstmt.setString(1,sysSequence.getTableName());
			pstmt.setLong(2,sysSequence.getSequenceId());
			pstmt.setString(3,sysSequence.getTableDesc());
			pstmt.setInt(4,sysSequence.getIncrementNum());
			pstmt.setTimestamp(5,DmValueUtils.dateToTimestamp(sysSequence.getCreateDate()));
			pstmt.setTimestamp(6,DmValueUtils.dateToTimestamp(sysSequence.getLastUpdate()));
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			 sysSequence.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
		}
		catch( SQLException sqle ){
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysSequence.java:insertIntoDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return sysSequence;
	}

	/**
	 * 保存该对象数据到数据库中.
	 */
	private static  void updateToDb(DAOFactoryImpl dao,String tableName,SysSequence sysSequence)  throws TransactionException{
		String updateSql =
		"UPDATE "+(tableName==null?"sys_sequence":tableName)+" SET " +
		"sequence_id=?,table_desc=?,increment_num=?,create_date=?,last_update=? "+
		"WHERE table_name=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_sequence":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,updateSql);
			pstmt.setLong(1,sysSequence.getSequenceId());
			pstmt.setString(2,sysSequence.getTableDesc());
			pstmt.setInt(3,sysSequence.getIncrementNum());
			pstmt.setTimestamp(4,DmValueUtils.dateToTimestamp(sysSequence.getCreateDate()));
			pstmt.setTimestamp(5,DmValueUtils.dateToTimestamp(sysSequence.getLastUpdate()));
			
			pstmt.setString(6,sysSequence.getTableName());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
			 sysSequence.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysSequence.java:updateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	
	/**
	 * 轻量级保存该对象数据到数据库中.
	 */
	private static  void liteUpdateToDb(DAOFactoryImpl dao,String tableName,SysSequence sysSequence)  throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		List<String> list = sysSequence.LIST_COL_UPDATED;
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE "+(tableName==null?"sys_sequence":tableName)+" set ");
        for (int i=0;i<list.size();i++){
        	if (i==0){
        		sb.append(list.get(i)+"=?");
        	}else{
				sb.append(","+list.get(i)+"=?");
			}
		}
		sb.append(" WHERE table_name=?");
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_sequence":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,sb.toString());
			String col = "";
			for (int i=0;i<list.size();i++){
				col = list.get(i);
				DmReflectUtils.DAOLiteSaveReflect(pstmt,sysSequence,i+1,SysSequence.MAP_COL_NAME.get(col),SysSequence.MAP_COL_TYPE.get(col));
			}
			
			col = "table_name";
			DmReflectUtils.DAOLiteSaveReflect(pstmt,sysSequence,list.size()+1,SysSequence.MAP_COL_NAME.get(col),SysSequence.MAP_COL_TYPE.get(col));
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();
			else
			 pstmt.executeUpdate();
			sysSequence.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysSequence.java:liteUpdateToDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try { if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}
	


	/**
	 * 从数据库装入该对象所需要的数据
	 */
	private static SysSequence selectFromDb(DAOFactoryImpl dao,String tableName,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		SysSequence sysSequence= null;
		try {
			String loadSql =
			"SELECT table_name,sequence_id,table_desc,increment_num,create_date,last_update FROM "+(tableName==null?"sys_sequence":tableName)+" "+(whereSql==null?"WHERE table_name=?":whereSql);
			con = dao.getTransactionController().getConnection((tableName==null?"sys_sequence":tableName),"read");
			pstmt = con.prepareStatement(loadSql);
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
			sysSequence= new SysSequence(DmValueUtils.nullToStr(rs.getString("table_name")),rs.getLong("sequence_id"),DmValueUtils.nullToStr(rs.getString("table_desc")),rs.getInt("increment_num"),rs.getTimestamp("create_date"),rs.getTimestamp("last_update"));
			sysSequence.CURRENT_TABLE_NAME = (tableName==null?null:tableName);

			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysSequence.java:selectFromDb(): ", sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return sysSequence;
	}
	/**
	 * 轻量级载入对象.
	 */
	private static SysSequence liteSelectFromDb(DAOFactoryImpl dao,String tableName,String[] colList,String whereSql,Object[] paramList) throws TransactionException{
		Connection con = null;
		PreparedStatement pstmt = null;
		SysSequence sysSequence= null;
        StringBuilder sb = new StringBuilder();
        sb.append(" select ");
        for (int i=0;i<colList.length;i++){
        	if (i==0) {
        		sb.append(colList[i]);
        	}else{
				sb.append(","+colList[i]);
			}
		}
		sb.append(" FROM "+(tableName==null?"sys_sequence":tableName));
		sb.append(" ").append(whereSql==null?"WHERE table_name=?":whereSql);
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_sequence":tableName),"read");
			pstmt = con.prepareStatement(sb.toString());
			if (paramList != null && paramList.length > 0) {
				for (int i = 0; i < paramList.length; i++) {
					DmReflectUtils.CommandUpdateReflect(pstmt, i + 1, paramList[i]);
				}
			}
			ResultSet rs = pstmt.executeQuery();
			if (rs.next()) {
				sysSequence = new SysSequence();
				String col = "";
				for (int i=0;i<colList.length;i++){
					col = colList[i];
					DmReflectUtils.DAOLiteLoadReflect(rs,sysSequence,col,SysSequence.MAP_COL_NAME.get(col),SysSequence.MAP_COL_TYPE.get(col));
				}
				sysSequence.CURRENT_TABLE_NAME = (tableName==null?null:tableName);
			}
			rs.close();
		}
		catch( Exception sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysSequence.java:liteSelectFromDb(): " , sqle );
		}
		finally {
			try {  pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
		return sysSequence;
	}

	
	/**
	 * 删除数据。
	 */
	public static void delete(DAOFactoryImpl dao,String tableName,SysSequence sysSequence)  throws TransactionException
	{
		deleteFromDb(dao,tableName,sysSequence);
	}

	/**
	 * 直接从数据库中删除数据.
	 */
	private static void deleteFromDb(DAOFactoryImpl dao,String tableName,SysSequence sysSequence)  throws TransactionException
	{
		String deleteSql = 
		"DELETE FROM "+(tableName==null?"sys_sequence":tableName)+" WHERE table_name=?";
		Connection con = null;
		PreparedStatement pstmt = null;
		try {
			con = dao.getTransactionController().getConnection((tableName==null?"sys_sequence":tableName),"write");
			pstmt = dao.getBatchUpdateController().prepareStatement(con,deleteSql);
			pstmt.setString(1,sysSequence.getTableName());
			
			if (dao.getBatchUpdateController().getBatchStatus())
			 pstmt.addBatch();			
			else
			 pstmt.executeUpdate();
		}
		catch( SQLException sqle ) {
			logger.error(sqle.getMessage(),sqle);
			throw new TransactionException("TransactionException in DbSysSequence.java:deleteFromDb(): " , sqle );
		}
		finally {
			try {  if (!dao.getBatchUpdateController().getBatchStatus()) pstmt.close(); }
			catch (Exception e) { logger.error(e.getMessage(),e); }
			try {  if (dao.getTransactionController().isAutoCommit()) con.close();   }
			catch (Exception e) { logger.error(e.getMessage(),e); }
		}
	}

	

}